### ISSUE TITLE
プレイヤー上で左右スワイプでシーク

### ISSUE THREAD

**Issue by tor4kichi** [tor4kichi/Hohoema#192]
スワイプ量とシークする秒数の感覚が把握できていないので実装済みアプリを探して使用感を調査が必要です。

**Comment by tor4kichi** [comment]
タッチデバイスでの操作性を大きく向上できる可能性があるため、早めに対応したいです。

**Comment by kamakurawpuser** [comment]
Perfect Tubeが対応していますね

**Comment by tor4kichi** [comment]
だいぶ遅くなりましたが対応しました。0.13.2 の更新で適用予定です。
