### ISSUE TITLE
検索の「～順」の指定を変えても「投稿が新しい順」のまま結果が表示される

### ISSUE THREAD

**Issue by tor4kichi** [tor4kichi/Hohoema#223]
実際に「人気が高い順」で検索結果が取れているか、またはタイトル表記だけが間違っているのか、確認が必要です。

**Comment by tor4kichi** [comment]
人気の高い順だけでなく動画再生数などのソートも上手く行えていないようです。

マイリストも含めて本家の検索ページの検証とOpenNiconico側も含めた動作チェックが必要です。

**Comment by tor4kichi** [comment]
検索結果に検索オプションが反映されていなかった問題を修正しました。
ただし、まだ「～の少ない順」などの「Accending（昇順）」が正常に反映されていません。

**Comment by hooky360** [comment]
すみません、別件で「検索オプションはちゃんと機能している」と報告しましたが、こちらにある通り昇順検索は出来ていませんでした。確認不足でした
使い方が分かっていないのですが、このトピックが閉じていないという事はこの問題は既知であり、かつ継続中という事ですよね？

**Comment by tor4kichi** [comment]
自分も半ば失念してましたが、継続してます。

#496 の件はXboxOneで検索結果画面が表示すら出来ないことを問題にしていた課題になるので、こちらはこちらで全プラットフォームでの検索オプション反映の正常性の課題として対応しています。

善意で確認頂いたことですし、あまりお気になさらず。ご報告ありがとうございます。

**Comment by tor4kichi** [comment]
【検索挙動に関するメモ】マイリスト検索、検索されないワードで検索をかけると「現在、混雑しています」という表示が出て結果が表示されず、十秒ほど時間を空けて再アクセスすると検索結果が正常に表示された。

（UX上アプリのバグと取られる可能性があるかもね）

**Comment by tor4kichi** [comment]
desc/ascではなくd/aで検索しなければいけない部分が間違っていたようです。

**Comment by tor4kichi** [comment]
キーワード、タグ、コミュニティ、生放送の検索で「昇順」オプション（～が少ない順、等）が機能しない問題に対応しました。（生放送は降順昇順が逆として扱われていました。お恥ずかしい限り。）

マイリストの検索オプションについては 公式の「マイリスト検索オプションの仕様更新 (#549)  」を鑑みた上で、昇順オプションの削除を行っています。

**Comment by tor4kichi** [comment]
公式との検索オプションの実装量に差がある状態ですが、検索順が指定とズレているという状況は解消できたと思いますのでこちらのIssueはアップデートのリリース後に閉じたいと思います。

**Comment by tor4kichi** [comment]
0.11.0 にて対応を完了したためこの課題は閉じたいと思います。

@hooky360 さんご協力頂きありがとうございました。

（バグ修正の確認報告は不要です。まだ問題が継続している場合にご報告頂けるとありがたいです）
