### ISSUE TITLE
リスト再生で未対応動画や削除動画をスキップできる仕組みを入れてほしい

### ISSUE THREAD

**Issue by kakkou** [tor4kichi/Hohoema#470]
マイリストの再生などで未対応動画や削除動画をしようとすると連続再生が停止してしまいます。
また未対応警告ダイアログが表示されていると右上のリスト表示の右左矢印も機能しない為
手動で動画を送ることもできません。

**Comment by tor4kichi** [comment]
連続再生の停止してしまう事態に対応できてませんでしたね。タイトル通り、再生できない再生リストアイテムは常にスキップする機能を導入して対応したいと思います。

また、未対応警告の表示がプレイヤー上の再生リスト表示と被ってしまう点も別Issueとして修正対応していきます。

**Comment by tor4kichi** [comment]
非対応動画の場合、自動スキップが常に行われるように機能を追加しています。ただ、無通知でスキップするようになっているので、非対応動画についてスキップ機能有効化の確認UIを追加予定です。

削除動画の場合、自動スキップをしつつ、トースト通知を通じて動画が削除された旨を通知し、ローカルマイリストのアイテムであれば自動で削除するようにしています。（ニコ動側のマイリストに対してはノータッチ）

これらの変更は0.9.1で適用される予定です。

（別Issueで再生リストと未対応動画の警告表示の表示順バグについても対応しましたが、現状では非対応動画は常に自動スキップされるため、プレイリストの最後のアイテムでリピートがOFFになっている等、未対応警告の画面は確認できない形になっています。一応直してますよーということで）
