### ISSUE TITLE
XboxOneで検索が利用できない？

### ISSUE THREAD

**Issue by tor4kichi** [tor4kichi/Hohoema#496]
PC環境では再現できず。

具体的にどういう問題があるのか報告を待って対応します。

**Comment by hooky360** [comment]
試してみましたが、キーワード検索・タグ検索・プレイリスト検索・コミュニティ検索・ニコ生検索及び検索オプション全て機能しているように見えます

**Comment by tor4kichi** [comment]
確認頂きありがとうございます。オプションまで含めて確認ありがたいです。

XboxOneでの検索は問題なさそうですね。

この課題はストアレビューで問題を指摘頂いたものですが、問題があるという方からはレビューの応答を拒否されていて進展が望めないようなので一旦この課題は閉じようかと思います。
