### ISSUE TITLE
フォロー追加が正常に行えない

### ISSUE THREAD

**Issue by tor4kichi** [tor4kichi/Hohoema#502]
タグのフォローが機能していないようです。

最大登録数到達時の情報表示が必要という可能性も含めて、問題を調査したいです。

追記
ニコレポ #529 と タグレポ #530 の対応のため、こちらも優先して対応していきたいです。

**Comment by hooky360** [comment]
ストアで報告した者です。
以前のバージョンでは
Hohoemaからタグをフォローしてもフォローボタンの色は変わるが、「フォロー中のタグ」の画面に出てこない
という動作だったと思うのですが、ひょっとしたら記憶違いかもしれません。
0.9.11では「タグのフォローを試行するが失敗する」という動作です。

ただ、本家サイトでタグをフォローするメリットはタグレポを見られる（新着チェックが楽）事だと思うので、
フィードと検索履歴の記憶がある現状のHohoemaで不足はない気もします。

**Comment by tor4kichi** [comment]
諸々了解しました。タグのフォロー機能はサポートを続けつつ、ゆるりと対応していきたいと思います。

（フィードや検索履歴の見やすさ改善も、と手を伸ばしたいところですがそちらはまた追々に。）

**Comment by tor4kichi** [comment]
コミュニティのフォローも利用できないようです。タグのフォローと合わせてこちらで対応してイキたいと思います。

**Comment by tor4kichi** [comment]
コミュニティのフォローについて、フォロー追加・削除の両方で操作が出来ない問題があったため対応しました。

コミュニティフォローの追加削除にはサーバー側からレスポンスが帰ってくるまで4~5秒ほど掛かるようです。

タグのフォローについては問題を再現できなかったため、特に作業をしていません。
