### ISSUE TITLE
シャッフル再生が機能していない

### ISSUE THREAD

**Issue by kakkou** [tor4kichi/Hohoema#545]
プレイリストがシャッフル状態になっていると動画再生終了時or動画送りのボタンを押した際に次の動画へ遷移しません。

**Comment by tor4kichi** [comment]
報告ありがとうございます。確認しました。

0.10.4 にて修正予定になるよう対応していきます。

**Comment by tor4kichi** [comment]
こちらの修正も適用した 0.10.4 の更新が公開されました。この課題は一旦閉じますが、何かあればまたコメント頂けるとありがたいです。
