### ISSUE TITLE
プレイリストに非公開設定の動画があると再生時にスキップされず連続再生が停止する

### ISSUE THREAD

**Issue by kakkou** [tor4kichi/Hohoema#577]
また非公開設定の動画はHohoemaのマイリスト上ではDeleted表記になっています。

**Comment by tor4kichi** [comment]
報告頂きありがとうございます。

原因としては、非公開動画の判定が削除動画と同様に扱われている点が一つ。それとプレイヤー上での削除動画検出後の自動遷移の動作が動画再生処理内の別のエラーで阻害されてしまっていた、という二つのエラーが重なっているようです。

対応していきます。
