### ISSUE TITLE
投稿者削除の動画を再生すると削除動画が流れる

### ISSUE THREAD

**Issue by kakkou** [tor4kichi/Hohoema#593]
v0.11.8で確認。
削除前キャッシュが無い場合などはスキップするようにはできないでしょうか？

また削除動画は最後まで再生されても連続再生が停止するようです。

**Comment by tor4kichi** [comment]
削除動画は飛ばせるようにってお話は以前もありましたが、対応漏れてましたね。
対応します。

**Comment by tor4kichi** [comment]
0.11.9にて対応しました。また問題ありましたらお知らせください。

**Comment by kakkou** [comment]
対応ありがとうございます。
0.11.9の分離再生ビュー状態で確認したところ
管理人削除動画とユーザー非公開動画がスキップされないようです。

下記URLは確認再生不可動画の確認に使ったマイリストになります。
http://www.nicovideo.jp/mylist/60424813

また削除動画の通知がでるとメインウィンドウの選択マイリストの表示からマイリストTOPメニューに戻ったりします。

**Comment by tor4kichi** [comment]
スキップできていない動画あるようで、再度確認して対応していきます。
確認のマイリスト助かります。ありがとうございます。 

マイリストTOPに戻ってしまうのは、バグですね。こちらは別の課題 ( #596 ) にて対応していきます。

**Comment by tor4kichi** [comment]
自動スキップできてなかった原因はHTML5プレイヤーページの解析エラーの影響でした。まずその点を修正しています。（動画サイズについて整数値型でnullを受け取れない、といった例外がでてました）

また、動画サムネイル情報取得の段階で削除動画とわかっている場合に、動画再生準備の早い段階で自動スキップが掛かるように変更しています。

再生不可動画の表示の方 #595 でも触れましたが、本丸である管理者削除と投稿者非公開について手元ではチェックできていません。
