### ISSUE TITLE
マイリストの再生不可動画の表示情報についての要望

### ISSUE THREAD

**Issue by kakkou** [tor4kichi/Hohoema#595]
0.11.9で確認しましたところマイリスト上の表記は以下のようになっています。

- 投稿者/権利者削除動画
　動画情報あり
　Delete表記
- 非公開動画/管理者削除動画
　動画情報なし
　Delete表記

現在動画情報のないユーザー非公開動画/管理者削除動画のタイトル名も再生ビューだと
表示されているのでもし可能であればタイトルを表示することはできないでしょうか。

また再生不可能な上記動画群を区別できるよう表記を分けることは可能でしょうか？
(Deleted表記の文言を変えてもらう等)

下記URLは参考までに再生不可能動画4種をそろえたマイリストになります
http://www.nicovideo.jp/mylist/60424813

**Comment by tor4kichi** [comment]
改めて調べてみたところ、対応は可能だと思います。

現在、動画のサムネイル情報は

```
http://ext.nicovideo.jp/api/getthumbinfo/[動画ID]
```

を利用して取得していますが、3DS等で使われる動画情報取得のAPIである

```
http://api.ce.nicovideo.jp/nicoapi/v1/video.info?v=[動画ID]
```

を利用することで削除理由のコード番号が取れるようになっていますので、削除理由の表記ができるようになると思います。

また、後者APIであればタイトルも取得可能なようです。

対応していきます。

**Comment by tor4kichi** [comment]
0.11.11 にて削除理由の簡易表示を動画リスト全般で行うよう表示を追加しました。 #593 も合わせて対応しています。

一部、未確認です。管理者削除と投稿者非公開は他ユーザーマイリスト取得APIや検索APIではリストデータから省かれていて取得できないため、確認できていません。

また、削除動画と似た挙動として、公式コンテンツで公開期限が設定されていて公開期限を過ぎた動画も同様の対応をしています。
