### ISSUE TITLE
[v0.13.3]フォローボタンが動作しない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#622]
**報告内容：**
「ユーザー動画」や「マイリスト」などに設置してあるフォローボタンをクリックしても、フォローが有効にならないようです。
少なくとも、フォローボタンをクリックしてもチェックマークが付きませんし、左メニューのフォローの中にも、フォローボタンをクリックして追加したつもりの動画やマイリストが追加されていないことを確認しています。

**環境：**
- Windows 10 Pro 1709
- Hohoema v0.13.3

**Comment by tor4kichi** [comment]
フォローが出来ない問題があるようですね。

こちらの環境ではユーザーやマイリストのフォロー登録が問題なくできているので、詳細な情報を頂きたいところです。

ですので以下の点についてお聞かせいただけると助かります

* マイリストやユーザーにはフォロー上限数がありますが、上限に達していませんか
* フォロー登録した後、アプリ内での追加位置が最後尾になっているため見逃しをされていないか（ただしアプリ再起動後になると最後に追加したアイテムが先頭に来ます）

**Comment by kometchtech** [comment]
以下に回答します。

> - マイリストやユーザーにはフォロー上限数がありますが、上限に達していませんか

フォロー欄の画像を添付します。登録数を見ると上限までは来ていないと認識しています。
![comu](https://user-images.githubusercontent.com/5137077/36943546-bca7e0ec-1fce-11e8-851a-0eaef2682e3c.JPG)
![tag](https://user-images.githubusercontent.com/5137077/36943547-bcd5e1b8-1fce-11e8-9b31-ed2f66f9aaf8.JPG)
![user](https://user-images.githubusercontent.com/5137077/36943548-bd02ee4c-1fce-11e8-9c31-6b11b9ba4d5e.JPG)
![mylist](https://user-images.githubusercontent.com/5137077/36943549-bd279c38-1fce-11e8-8826-8a7c468ce697.JPG)

> - フォロー登録した後、アプリ内での追加位置が最後尾になっているため見逃しをされていないか（ただしアプリ再起動後になると最後に追加したアイテムが先頭に来ます）

はい、フォローボタンをクリックして、その後フォロー欄に移動、各項目を確認しましたが、フォローを押したユーザーやマイリストは登録されていませんでした。

**Comment by tor4kichi** [comment]
ご確認ありがとうございます。間違いなくアプリ側の問題のようですね。

更なるご協力をお願いできるとありがたいのですが、アプリ側での問題抽出の準備ができていませんので、一旦、こちらで問題の解消に努めたいと思います。

**Comment by kometchtech** [comment]
お手数おかけします。
提供する必要がある情報がありましたらご連絡ください。
