### ISSUE TITLE
[v0.13.4] 操作中に強制終了する

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#631]
**報告内容：**
動画を検索して動画を再生して、再度検索して動画を再生して、を何度か繰り返していると、検索をクリックした際に、右ペインが白いまま反応が無くなり、アプリケーション自体が終了する。

```
障害が発生しているアプリケーション名: NicoPlayerHohoema.exe、バージョン: 1.0.0.0、タイム スタンプ: 0x5a9b4fa6
障害が発生しているモジュール名: Windows.UI.Xaml.dll、バージョン: 10.0.16299.248、タイム スタンプ: 0xc27fa098
例外コード: 0xc000027b
障害オフセット: 0x000000000047c21a
障害が発生しているプロセス ID: 0x18f0
障害が発生しているアプリケーションの開始時刻: 0x01d3b60399d41d02
障害が発生しているアプリケーション パス: C:\Program Files\WindowsApps\18803tor4kichi.Hohoema_0.13.4.0_x64__4pjhgkyx0a7ee\NicoPlayerHohoema.exe
障害が発生しているモジュール パス: C:\Windows\System32\Windows.UI.Xaml.dll
レポート ID: e6917eec-76d8-4d8b-88f2-f6a6252b3415
障害が発生しているパッケージの完全な名前: 18803tor4kichi.Hohoema_0.13.4.0_x64__4pjhgkyx0a7ee
障害が発生しているパッケージに関連するアプリケーション ID: App
```

**環境：**

- Windows 10 Pro 1709
- Hohoema v0.13.4

**Comment by tor4kichi** [comment]
こちらでは問題が再現できませんでした。確実に問題を再現する方法はありますか？

**Comment by kometchtech** [comment]
すみません、何回切り替えているうちに発生するというだけで、確実に発生させる方法は見つかっていません。

2018/03/08 18:36 "kiichi toura" <notifications@github.com>:

**Comment by tor4kichi** [comment]
そうでしたか。ありがとうございます。

しかし原因の見当つかないので難しそうですね…。頭の片隅に置きつつ様子見たいと思います。

**Comment by kometchtech** [comment]
提供できる情報がなくて申し訳ありません。
ただ、0.13.3ではほとんど発生した記憶がなく、0.13.4から多く発生しているという状況です。
再現手順など見つかりましたら追記します。

2018/03/08 18:51 "kiichi toura" <notifications@github.com>:

**Comment by kometchtech** [comment]
更新ありがとうございます。

さっそく、v0.13.6にアップデートしてみました。
少なくとも普段使うようにちょこちょことメニューを切り替えた感じでは強制終了することは、今のところありませんでした。
（といっても起動数回ですが）

以前のように頻繁？に落ちるようであれば、改めてissueとして連絡しようと思います。
ご対応ありがとうございました。

**Comment by tor4kichi** [comment]
一度閉じてしまいましたが、再度症状確認したため再オープンさせてください🙏💦
（返信不要です。進展あればまたこちらで報告していきます）

**Comment by kometchtech** [comment]
ご報告遅れましたが、こちらも症状を確認しました。
以前よりは発生の頻度は格段に下がっているのですが・・・

```
障害が発生しているアプリケーション名: NicoPlayerHohoema.exe、バージョン: 1.0.0.0、タイム スタンプ: 0x5ab8e33b
障害が発生しているモジュール名: Windows.UI.Xaml.dll、バージョン: 10.0.16299.248、タイム スタンプ: 0xc27fa098
例外コード: 0xc000027b
障害オフセット: 0x000000000047c21a
障害が発生しているプロセス ID: 0x6574
障害が発生しているアプリケーションの開始時刻: 0x01d3c83a69d1712d
障害が発生しているアプリケーション パス: C:\Program Files\WindowsApps\18803tor4kichi.Hohoema_0.13.7.0_x64__4pjhgkyx0a7ee\NicoPlayerHohoema.exe
障害が発生しているモジュール パス: C:\Windows\System32\Windows.UI.Xaml.dll
レポート ID: 6285c447-bd40-46b2-b3ff-669d989da5f0
障害が発生しているパッケージの完全な名前: 18803tor4kichi.Hohoema_0.13.7.0_x64__4pjhgkyx0a7ee
障害が発生しているパッケージに関連するアプリケーション ID: App
```

**Comment by kometchtech** [comment]
今のところですが、v0.13.13では強制終了を確認していません。

**Comment by tor4kichi** [comment]
だいぶ間が空いてしまいましたが問題なく使えてるかと思いますのでクローズしますー_(._.)_

**Comment by kometchtech** [comment]
@tor4kichi 
すみません、放置していて忘れていましたm(__)m
今は問題なく使用できていますのでクローズで大丈夫です。
