### ISSUE TITLE
[要望] マイリストの再読み込みを行えるようにしてほしい

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#637]
動画情報から、ユーザーが公開しているマイリストなどをクリックし、Hohoemaのマイリストへ遷移するとき、たまにですが白い画面になったままリストが表示されないときがあります。
その時は、再度、動画情報からマイリストを選択する、という手順が必要になり少しばかり不便です。

ですので、右上にある「フォロー」などがあるメニューにマイリストの再読み込み、などを追加してほしいです。

参考：
http://www.nicovideo.jp/mylist/32089757
※たぶん、マイリスト件数が500件もあるためだと思うのですが・・・

**Comment by tor4kichi** [comment]
確かに更新ボタン欲しいですね。対応します。

マイリストが読み込めない部分が根本なので、そちらも確認しつつやっていければと思います。

**Comment by kometchtech** [comment]
ありがとうございます。

実装されるのを楽しみにしております。

2018年3月15日 10:46 kiichi toura <notifications@github.com>:

**Comment by tor4kichi** [comment]
v0.13.6 の更新にてマイリストの更新ボタン対応しました。

マイリストが読み込まれないことがある問題についてまた別途対応していきます。

**Comment by kometchtech** [comment]
更新ありがとうございます。
更新ボタンが付いたことで、個人的にだいぶ使いやすくなりました。

ご対応ありがとうございました。
