### ISSUE TITLE
[v0.13.6] 検索履歴の順番が変わらない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#639]
**報告内容：**
v0.13.5までは、検索した文字列で最後に使用したものは一番に上に来ていたと思うのですが、v0.13.6では変わらず、追加した順番になっているようです。
リリースノートを確認した限りではこの件については触れられていなかったのでご報告いたします。

**環境：**
- Windows 10 Pro 1709
- Hohoema v0.13.6

**Comment by tor4kichi** [comment]
ご指摘の通りv0.13.5の動作の方が正しいです。内部DBの入れ替えの際に並び替え部分の移植が抜けていたようです。対応します。

**Comment by tor4kichi** [comment]
v0.13.7 の更新で修正が反映されたかと思います。問題が継続するようでしたらまたお知らせくださいませ。

**Comment by kometchtech** [comment]
本日アップデートが来ていることを確認しましたので、0.13.7にアップデートしてみました。
検索履歴で使用した順に並び変わることを確認しました。

素早いご対応ありがとうございました。

2018-03-27 9:28 GMT+09:00 kiichi toura <notifications@github.com>:

**Comment by tor4kichi** [comment]
こちらこそ丁寧なご報告いただきありがとうございます。（解決できたようなのでクローズしますね）
