### ISSUE TITLE
[v0.13.7] マイリストの動画が自動的に次に移動し再生されてしまう

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#653]
**報告内容：**
以下のようなアプリ側の設定になっているにも拘わらず、ユーザーのマイリストから再生すると、新しい方から古い方に自動的に移動し再生されてしまいます。

[次](https://github.com/tor4kichi/Hohoema/wiki/%E9%80%A3%E7%B6%9A%E5%86%8D%E7%94%9F%E3%81%AE%E4%BD%BF%E3%81%84%E6%96%B9)にある”自動再生”には該当しないと思っていますが、どうなんでしょうか？

![temp](https://user-images.githubusercontent.com/5137077/38158581-50c60764-34d2-11e8-9e5e-66d32fce4808.JPG)

**環境：**
- Windows 10 Pro 1709
- Hohoema v0.13.7

**Comment by tor4kichi** [comment]
動画の次移動に関して動作が競合する部分ですね。それぞれ説明させてください。

まず「次パート動画を自動検出して移動」は動画情報の投稿者説明文を解析して次パート動画IDを検出する処理しています。「あとで見るプレイリスト」上で再生している時にプレイリストが空になったタイミングで、自動で次動画を検出しています。

一方でマイリストの連続再生については、動画プレイヤー上でマイリスト動画一覧を右側に表示した際の、上側に表示されている連続再生オプションのアイコンの状態によって決定しています。（左から順にシャッフル、リピート、再生方向となってます）

具体的にはマイリストの連続再生オプションに「上矢印（または下矢印）」があると思いますが、この矢印の状態によってマイリストの連続再生方向が決まっています。上矢印なら古い→新しい、下矢印なら新しい→古い、といった具合です。（デフォルトでは下矢印、新しい→古い順）

提示頂いた画像の下側にグレーアウト表記している「マイリストから視聴している場合は無効」という文言は「動画情報の投稿者説明文から次パート動画を検出する動作はマイリストから再生している時に限って動作させませんよ」ということを意図しています。

（マイリスト連続再生と次パート検出の動作競合について（あるいはマイリストの連続再生自体が）直感的に理解しづらいことが問題だと感じたので改善点としたいと思います）

**Comment by kometchtech** [comment]
ご指摘ありがとうございます。また解説ありがとうございます。
"現在のプレイリスト"として制御されているんですね・・・盛大に勘違いしていました。

> （マイリスト連続再生と次パート検出の動作競合について（あるいはマイリストの連続再生自体が）直感的に理解しづらいことが問題だと感じたので改善点としたいと思います）

ありがとうございます。
そうですね、個人的には単体再生と、"マイリストの連続再生"の有効が切り替えられれば良いかな、と思います。

**Comment by tor4kichi** [comment]
誤解を招く表現やUIだというのに気付かされた貴重なご意見でした。ありがとうございます。

次パート検出も連続再生の関連部分として設定UI、プレイリストUIの表現を考えて行こうかと思います。

> 単体再生と、"マイリストの連続再生"の有効が切り替えられれば

こちらも実は、リピート再生の設定で「全体リピート」→「単体リピート」→「１順のみ（リピート無し）」と設定が切り替えられるんですが、わかりづらいんだろうなということで、連続再生UIについてちゃんと表現していこうと思います。

UIの改善については別件対応としていきますのでこちらのissueは閉じますね

**Comment by kometchtech** [comment]
ご丁寧にありがとうございます。

closeしていただいて大丈夫です。

2018年3月31日(土) 13:24 kiichi toura <notifications@github.com>:
