### ISSUE TITLE
HTMLエンティティがデコードされていない

### ISSUE THREAD

**Issue by mrtska** [tor4kichi/Hohoema#657]
![image](https://user-images.githubusercontent.com/6443854/38260227-fd52b5aa-37a1-11e8-9fd6-ccf9495bbfd9.png)

ニコニコではよくある &amp; です。%#039;もありますね（私もデコード忘れでそのまま表示されていました・・・）

修正コードも、と思いましたがビルドできなかったので報告まで・・・

**Comment by tor4kichi** [comment]
ありがとうございます。Webあるあるですね。（APIごとに解析を組んでいると時々HTMLエンコード対策が抜けてしまう…）

こちらで対応やれますので大丈夫です。

（ビルドが通らない件はオープンソースでやってる意味薄れてしまうのでなんとかしたいですね…）

**Comment by tor4kichi** [comment]
v0.13.10 の更新で対応しました👌
（System.Net.WebUtility.HtmlDecode() を通すだけの簡単な修正でした）

補足として、オススメ動画APIのデータだと動画タイトル表示が長い場合に省略される場合があるようです。ただ追加情報取得はサーバー負担になるので辞めておこうと思ってそのままにしています。
