### ISSUE TITLE
Suggestion: Automatically enter fullscreen mode when playing a video

### ISSUE THREAD

**Issue by JasonWei512** [tor4kichi/Hohoema#659]
(My Japanese is poor so I have to write in English, sorry😂)
There’s one feature I like about Microsoft’s “Movies & TV” app: On PC, if the app window is maximized and you start playing a video, the app will automatically enter fullscreen mode; On Windows 10 Mobile if you start playing a video, the app will also enter fullscreen mode (so the navigation bar will hide); And when you exit playing, the app will exit fullscreen mode. 

![ilst](https://user-images.githubusercontent.com/16899918/38298600-6959e4ac-382a-11e8-9c8a-88e333104b93.jpg)
This is quite convenient when playing a video because you don’t need to click the fullscreen button or hide the navigation bar manually. Hope this feature will be brought to Hohoema (or make it an option in settings) .

```
ApplicationView CurrentView = Windows.UI.ViewManagement.ApplicationView.GetForCurrentView();
String DeviceType = Windows.System.Profile.AnalyticsInfo.VersionInfo.DeviceFamily;


// When playing a video   
if(DeviceType == "Windows.Mobile")
{
    CurrentView.TryEnterFullScreenMode();
}
else if(DeviceType == "Windows.Desktop")
{
    if (CurrentView.AdjacentToLeftDisplayEdge && CurrentView.AdjacentToRightDisplayEdge)  // Check if the app window is maximized
    {
        CurrentView.TryEnterFullScreenMode();
    }
}
else if(DeviceType == "xxxxxx")
{
    //......
}


// When exit playing
CurrentView.ExitFullScreenMode();
```

@cotaku 希望B站UWP的自动全屏能改成这样，现在平板模式左右分屏的时候放视频也自动全屏有点蛋疼（

**Comment by tor4kichi** [comment]
thank you suggestion! very good idea!

so i will try merge that idea into current Hohoema implementation. (within "not option")

**Comment by cotaku** [comment]
@JasonWei512 that's a good idea! I didn't consider two much for tablet mode (because my old Surface is still on Windows 8.1 :p)

**Comment by tor4kichi** [comment]
i did it with v0.13.10 update! 

v0.13.10 の更新でこの提案を実装しました👍👍

基本は頂いたコード例を活用していますが、Hohoemaとして利用するために以下の点に配慮して実装しています。

* 「小窓表示」の際にフルスクリーンを解除
* 「アプリ起動時に全画面表示にする」という設定が有効な場合に、プレイヤーを閉じた際にフルスクリーンが解除されないようにする

一つだけ問題点として、別ウィンドウ（セカンダリウィンドウのプレイヤー）では自動フルスクリーン切り替えが失敗してしまうことを確認しています。ただし、タブレットやモバイルでは「別ウィンドウ表示＋自動フルスクリーン切り替え」を必要とする場面が少ないと思うので、対応しないつもりです。

モバイルでの使い勝手で問題あれば教えてください。

**Comment by JasonWei512** [comment]
Just tested on PC and Windows Phone, works fine. 谢谢茄子！
About the multiple windows problem, maybe you can ask @cotaku 😂 who is the developer of Bilibili UWP

**Comment by tor4kichi** [comment]
ビリビリの開発者さんって本当ですか！？ 知らなくてビックリしました！
本当に困ったら @cotaku さんに相談させて頂けると助かります😄

動作は問題ないようなのでissueはクローズしておきますね。今回は提案ありがとナス！ 謝謝！
