### ISSUE TITLE
A little problem with "横持ち固定" on Windows Phone

### ISSUE THREAD

**Issue by JasonWei512** [tor4kichi/Hohoema#663]
Situation: I locked my phone's rotation to portrait mode/縦 , and enabled "横持ち固定" in Hohoema. 
Then when I play a video, the [←10s] and [30s→] button disappeared:
![wp_ss_20180406_0004](https://user-images.githubusercontent.com/16899918/38402595-e290d824-398f-11e8-8b1b-fe526aab171d.jpg)
![wp_ss_20180406_0003](https://user-images.githubusercontent.com/16899918/38402597-e817323e-398f-11e8-8cd8-3bd37674f3a2.jpg)

When I disabled rotation lock and 横持ち固定:
![wp_ss_20180406_0002](https://user-images.githubusercontent.com/16899918/38402678-76591c56-3990-11e8-9200-cc76cae85884.jpg)

Seems like a problem with` <AdaptiveTrigger MinWindowWidth="xxx" />`

**Comment by tor4kichi** [comment]
横持ち固定であっても縦持ちとしてのウィンドウの横幅を参照しているために、いくつかボタンが非表示になっているようですね。

AdaptiveTrigger ではなく [AdaptiveTriggerLibrary](https://github.com/Herdo/AdaptiveTriggerLibrary)のControlWidthTrigger に置き換えれば対応できそうです。たぶん。

**Comment by tor4kichi** [comment]
v0.13.11 で修正しました
