### ISSUE TITLE
[v0.13.12] マイリスト名が見にくい

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#674]
**報告内容：**
テーマがLightの場合、マイリストで使用される文字色は黒だと思うのですが、背景が黒の動画が多く、それと同化してしまい、マイリスト名が判別しづらくなっている。できれば文字色を変更するか、マイリスト名が動画に被らない形で表示されてほしい。
![mylist](https://user-images.githubusercontent.com/5137077/39617607-4b8213b6-4fbb-11e8-8bd2-8e2171267be2.JPG)

**環境：**
Windows10 Pro 1803
Hohoema v0.13.12

関連：
https://github.com/tor4kichi/Hohoema/issues/647

**Comment by tor4kichi** [comment]
確かに読み取りづらいですね。了解しました！

**Comment by kometchtech** [comment]
お手数をおかけします。
できれば、という感じなのですが、今のように"フォルダ一覧？"のような表示形式と、公開マイリストのように、"詳細一覧？"のような表示形式が選択できるようだと嬉しいです。

**Comment by tor4kichi** [comment]
なるほど。

マイリストはフォルダ系のアイテムかなと思ってボックスな表示にしていますが、一方でマイリスト所有者や説明がわからないと、マイリストタイトルだけでは内容を判別しづらい問題がありそうですね。

ただ、開発都合として、XboxOneやモバイル含めた複数プラットフォーム対応を楽に回すことを優先したいので、表示形式の切り替え・選択には対応しないつもりです。（複雑化は避けたい）

表示統一しつつマイリストの説明を盛る方向で考えていこうかと思います。

**Comment by kometchtech** [comment]
> ただ、開発都合として、XboxOneやモバイル含めた複数プラットフォーム対応を楽に回すことを優先したいので、表示形式の切り替え・選択には対応しないつもりです。（複雑化は避けたい）

ユニバーサル対応はなにかと大変だと思いますので無理にご対応いただかなくても大丈夫です。（こうだったら良いな、ぐらいでしたので）

> 表示統一しつつマイリストの説明を盛る方向で考えていこうかと思います。

はい、こういうのが良いのでは、というアイディアがないので提示できないのですが、ご対応いただけば助かります。
