### ISSUE TITLE
[v0.13.27] マイリストのオプションメニューの[選択]が小さく表示される

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#683]
**報告内容：**
画像のようにマイリストの[もっと見る]を開くと、[選択]（だと思うのですが）だけが小さく表示されます。

![mylist](https://user-images.githubusercontent.com/5137077/40840414-8a2b27a6-65e1-11e8-984f-49de4389efdb.JPG)

**環境：**
Windows10 Pro 1803
Hohoema v0.13.27

**Comment by tor4kichi** [comment]
ご報告ありがとうございます。こちらでもOS version 1803のPCと1704のタブレットでも同様の表示を確認しました。

標準UIのCommandBarでアイテムの表示・非表示を操作した時に出てくるバグのようですね。選択時、非選択時で別々のCommandBarを使う形で対応してみようかと思います。
