### ISSUE TITLE
[v0.13.27] ローカルマイリストが作成できない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#685]
**報告内容**
動画から直接右クリックで[マイリストに追加]を選択し、新規作成から[ローカルマイリスト]を作成しようとしても、添付の画像のように[OK]が有効にならない。

![mylist](https://user-images.githubusercontent.com/5137077/41041684-ad918382-69da-11e8-8e58-68a3c000f013.png)

**環境：**
Windows10 Pro 1803
Hohoema v0.13.27

**Comment by tor4kichi** [comment]
ご報告ありがとうございます。

こちら別ウィンドウでプレイヤーを表示している場合に問題が起きることを確認しました。（メインウィンドウでプレイヤー表示している場合は普通にOK押せるようになりますね）

たぶんですが、別ウィンドウで表示してるのにメインウィンドウのスレッド同期スケジューラを使って入力を受け取ろうとしてしまってることが原因だと思います。

対応していきますー。

**Comment by kometchtech** [comment]
すみません、別ウィンドウで使用していることを書くのを忘れていました。
お手数をおかけしますがよろしくお願いします。

**Comment by kometchtech** [comment]
0.13.30 で別ウィンドウのプレイヤから、ローカルマイリストを作成できるようになっていることを確認しました。
ご対応いただきありがとうございます。
