### ISSUE TITLE
透過背景タイルのアイコンが表示されない

### ISSUE THREAD

**Issue by tor4kichi** [tor4kichi/Hohoema#689]

**Comment by tor4kichi** [comment]
修正しました。修正は v0.13.29 のアップデートから利用可能になる予定です。

原因としては、SecondaryTileのコンストラクタにアイコンURIを渡すだけだと不十分なようで、SecondaryTile.VisualElementsにある各解像度(150x150や310x150)のアイコンURIをセットアップしてやる必要があるようです。

またタイルのアプリ名表示がされてなかった問題も

```
SecondaryTile.VisualElements.ShowNameOnSquare150x150Logo = true;
```

を設定することで解決できるようです。

参考： https://docs.microsoft.com/en-us/uwp/api/windows.ui.startscreen.secondarytilevisualelements

**Comment by tor4kichi** [comment]
モバイルでのアイコン表示ができていないようです。再度調整していきます。

**Comment by kometchtech** [comment]
0.13.30 になってから、タイルにロゴも表示されなくなったように見えます。
ソフトウェア名だけ表示されていますね。

![hohoema](https://user-images.githubusercontent.com/5137077/41214001-c2782484-6d83-11e8-85d8-e45e1df45a23.png)

**Comment by kometchtech** [comment]
特に動作に影響があるようには見受けられないので、個人的には急ぎで対応していただかなくても大丈夫です。

**Comment by kometchtech** [comment]
新規でWindows10 1809をインストールする機会があったので、Hohoemaの新規インストールを試してみましたが、やはりタイルのアイコンは表示されないようです。

![hohoema](https://user-images.githubusercontent.com/5137077/46918121-e3810780-d008-11e8-8c3b-d2f64c91e38d.png)

バージョンはv0.14.6になります。
