### ISSUE TITLE
使えない

### ISSUE THREAD

**Issue by doreddono-to** [tor4kichi/Hohoema#701]
今日になってから使えなくなりました。
起動するとHohoemaのマークが出て止まります。

**Comment by tor4kichi** [comment]
はじめまして。

私の環境では問題なく使えているため doreddono-to さんの使用環境に依存した問題が起きていると思います。

急場の対応案として

* OSを再起動してからアプリの起動を試し下さい
* アプリの休止または再開の処理の最中にアプリがクラッシュし、アプリを再度起動した際に前回アプリ状態への復帰を試行してアプリが固まっている可能性があります。「アプリを起動→アプリを閉じる→アプリを起動…」を何度か繰り返すことで復帰するかもしれません
* それでもダメな場合は（もし可能であれば）アプリの再インストールをお試しください

再インストールする場合には[アプリデータのバックアップ](https://github.com/tor4kichi/Hohoema/wiki/%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E3%83%87%E3%83%BC%E3%82%BF%E3%81%AE%E3%83%90%E3%83%83%E3%82%AF%E3%82%A2%E3%83%83%E3%83%97%E6%96%B9%E6%B3%95)を推奨します。

正常に起動できなくなる以前に行なった操作でお気づきの点などありましたらお知らせ頂けると助かります。

**Comment by doreddono-to** [comment]
アドバイスどもです。PCを再起動したら治りました。
ここ最近終わるときは休止ばっかにしてたのがいけなかったかもしれません。

**Comment by tor4kichi** [comment]
解決されたようで良かったです。課題クローズしますね。
