### ISSUE TITLE
視聴履歴を30件以上表示できるようにしてほしい

### ISSUE THREAD

**Issue by doreddono-to** [tor4kichi/Hohoema#702]
以前から気になってたのですが視聴履歴が30個までしか表示されないのですがこれがデフォなんでしょうか？
あとピン留めした項目の名前の変更等ができるといいのですが。

**Comment by tor4kichi** [comment]
別々の案件なので分けて課題管理させてもらいます。こちらは視聴履歴として課題の改名、ピン留めの名前変更は別課題として建てます。

**Comment by tor4kichi** [comment]
ピン留めの件は #703 の方で対応を管理していきます。

**Comment by tor4kichi** [comment]
公式に合わせて履歴件数一般アカウント50件orプレミアム100件まで取れるようにできたほうが便利ですよね。

ただすぐに対応できる状況ではないの課題の整理だけになります。着手できるのはだいぶ先になると思います。

**Comment by tor4kichi** [comment]
こちらも対応完了したと思いますので一旦課題をクローズさせていただきます。
課題はいつでも再オープン可能ですので問題ありましたらお知らせください。
