### ISSUE TITLE
ピン留めのタイトルを変更したい

### ISSUE THREAD

**Issue by tor4kichi** [tor4kichi/Hohoema#703]

**Comment by tor4kichi** [comment]
@doreddono-to こんにちは、Hohoemaの開発者です。ご提案頂いていたピン留めのタイトル変更に対応しようかと思うのですが、「何故変えたいのか」が不明でどう変更するべきか悩んでます。「どういったピン留めのタイトルが不便で、どう変更したいのか」というケースについて出来る範囲で聞かせていただけませんか？

**Comment by tor4kichi** [comment]
内部的には「ラベル＋ページの種類」の２つを組み合わせてピン留めタイトルを決定しています。（例：猫 癒し（キーワード検索））

変更案としては、上書き用ラベルを追加設定できるようにして「ラベル＋ページの種類」を完全に置き換える形を考えてます。上書き用ラベルを削除したら元の表示に戻せる感じですね。

一週間ほど待ってお返事ないようなら上記案で進めようと思います。もしかして私が想定してないケースで問題が起きているようでしたらその時教えていだけたらまた別の方法を考えようかと。

**Comment by tor4kichi** [comment]
半ば自問自答みたいな形になってしまいましたが、0.14.10の更新にピン留めの表示名を変更できる機能を追加しました。問題あればお聞かせくださいな。

**Comment by doreddono-to** [comment]
対応どうもです。おかげで使いやすくなりました、ありがとうございました。
