### ISSUE TITLE
関連動画ページに「次の動画」が表示されない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#707]
#706 と関連があるか分かりませんが、このタイミングから、
関連動画に今まで表示されていた「次の動画」が表示されなくなりました。

また、このことから、次の動画への自動切換え？もされなくなったように思えます。

- v0.14.6
- Windows10 17763.55

**Comment by tor4kichi** [comment]
ご報告ありがとうございます。

動画情報の動画説明欄のHTMLから次動画を判定してますが、仰る通りでhttpのみを抽出してhttpsで始まるコンテンツを補足できていないようでした。

他のURL周りについてもチェックしつつ、日曜か月曜にはhotfixをリリースしようかと思います。

修正版リリースまで今しばらくお待ちくださいませー。

**Comment by kometchtech** [comment]
v0.14.7 で修正されていることを確認しました。
ご対応ありがとうございます。

- 関連動画欄に「次パート動画」が出ることを確認しました。
- 次パート動画への自動ジャンプが動作していることを確認しました。
