### ISSUE TITLE
検索オプションを切り替えても一回で切り替わらない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#715]
検索したりピン止めした検索の結果一覧で、検索オプションを切り替えても、
一覧がすぐに切り替わらないようです。
普段は”投稿が新しい順”にしているのですが、ほかのオプションに切り替えたときに、
反応するものとしないものがあります。

- "投稿が新しい順" -> "コメントが新しい順"　：反応しない
- "マイリストが多い順" -> "再生時間が長い順"　：反応しない

2回クリックしたりするとオプションが反映されて一覧が切り替わったりするのですが、
オプションの切り替え順を変えると、切り替わったりします。

0.14.10の前のバージョン（0.14.8かな）ではこの問題は発生しませんでした。
取り急ぎ「更新」を押せば問題はないです。

環境：
- Windows10 Pro 1809
- v0.14.10

**Comment by tor4kichi** [comment]
ご報告頂きありがとうございます。こちらでも同様の問題を確認しました。

検索結果ページなど動画リスト系ページに導入したページキャッシュ機能の影響だと思います。

そこまで深刻な問題というわけではないようですが、次の機能更新まで間が空きそうですのでhotfixとして早々に対応して出そうかと思います。

**Comment by kometchtech** [comment]
遅くなりました。
v0.14.11で問題が解消していることを確認しました。
ご対応ありがとうございました。
