### ISSUE TITLE
[0.15.0] コメントができない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#724]
ニコニコ動画に対してコメントを入力しようとしても、
何も反応せずコメントが入力できない状態です。
参考：【MMD艦これ】多摩がいるのはこんな鎮守府～18初秋イベ編そのいち【MMDドラマ】 http://nico.ms/sm34197673 

設定としては、
[コメントの投稿設定]
デフォルトで匿名(184)コマンドを有効にする
→オン/オフとも変わらず

念のためデバッグログも添付しますが、ろくな情報は見当たりませんでした。
[hohoema_UserMylist_2018-11-19_23-22-47.txt](https://github.com/tor4kichi/Hohoema/files/2595661/hohoema_UserMylist_2018-11-19_23-22-47.txt)

**環境：**
Windows10 1809
Hohoema 0.15.0

**Comment by tor4kichi** [comment]
毎度ありがとうございます。

動画のコメントできない問題は現在進行形で対応中で今週末には更新リリース予定です。

課題 → https://github.com/tor4kichi/Hohoema/issues/655

修正したコミットログ → https://github.com/tor4kichi/Hohoema/commit/21362465fc3501b86c4377ec35d2288d623dc7c8

ただ、方々から対応してと声が上がってる状態なのでこのまま課題一覧のトップに残しておいたほうが見やすいと思いますので、こちらはクローズしないで残しておきたいですが、いいでしょうか。

**Comment by kometchtech** [comment]
すみません、該当のissueを確認できていませんでした。

>ただ、方々から対応してと声が上がってる状態なのでこのまま課題一覧のトップに残しておいたほうが見やすいと思いますので、こちらはクローズしないで残しておきたいですが、いいでしょうか。

はい、 @tor4kichi さんが良いようにしていただければと思います。

**Comment by tor4kichi** [comment]
了解しました。ありがとうございます。

課題は重複してても問題が重要なんだという話で済みますので、お気になさらずー。

**Comment by kometchtech** [comment]
以下のバージョンにアップデートしましたが、`コメント投稿に失敗 ( error code:4)`と出力されますねー
**環境：**
v0.15.2

**Comment by tor4kichi** [comment]
0.15.3 の更新でプレミアム会員を示すフラグをコメント投稿情報に追加して対応しました。（テスト参加者向けにはすでに公開済みですが、一般公開は23日午後の予定です）

**Comment by kometchtech** [comment]
`v0.15.3`でコメント投稿ができることを確認しました。
ご対応ありがとうございました。
