### ISSUE TITLE
【動画再生画面】設定アイコンをクリックしても何も表示されない

### ISSUE THREAD

**Issue by nishizumi-lab** [tor4kichi/Hohoema#738]
動画再生画面において、設定アイコンをクリックしても何も表示されず、画質変更等できません。

【環境】
Hohoema ver0.15.3
Windows10 (1809)

**Comment by tor4kichi** [comment]
こちらの環境Windows 10 (1803)では問題が再現できないので手元の環境が揃うまで対応は後回しになりそうです。ひとまず問題について了解しました。

**Comment by nishizumi-lab** [comment]
あけましておめでとうございます。
いつもありがたく利用させていただいております。
最新版で設定ボタンを押すと下記のエラーメッセージが出ましたのでご報告いたします。

{
  "DeviceType": "Windows.Desktop",
  "OperatingSystem": "WINDOWS",
  "OperatingSystemVersion": "10.0.17763.195",
  "OperatingSystemArchitecture": "X64",
  "ApplicationVersion": "0.17.0.0",
  "Time": "2019-01-03T22:19:25.3890071+09:00",
  "RecentOpenedPageName": "NicoRepo",
  "ErrorMessage": "Unity.Exceptions.ResolutionFailedException: Resolution of the dependency failed, type = 'NicoPlayerHohoema.ViewModels.PlayerSidePaneContent.SettingsSidePaneContentViewModel', name = '(none)'.\nException occurred while: Calling constructor NicoPlayerHohoema.ViewModels.PlayerSidePaneContent.SettingsSidePaneContentViewModel(NicoPlayerHohoema.Models.NGSettings ngSettings, NicoPlayerHohoema.Models.PlayerSettings playerSettings, NicoPlayerHohoema.Models.PlaylistSettings playlistSettings).\nException is: InvalidOperationException - NoMatch\n-----------------------------------------------\nAt the time of the exception, the container was: \r\n  Resolving NicoPlayerHohoema.ViewModels.PlayerSidePaneContent.SettingsSidePaneContentViewModel,(none)\r\n  Calling constructor NicoPlayerHohoema.ViewModels.PlayerSidePaneContent.SettingsSidePaneContentViewModel(NicoPlayerHohoema.Models.NGSettings ngSettings, NicoPlayerHohoema.Models.PlayerSettings playerSettings, NicoPlayerHohoema.Models.PlaylistSettings playlistSettings)\r\n ---> System.InvalidOperationException: NoMatch\r\n   at NicoPlayerHohoema!<BaseAddress>+0x1c2d0fa\r\n   at NicoPlayerHohoema.ViewModels.PlayerSidePaneContent.SettingsSidePaneContentViewModel.<>c.<.ctor>b__0_1(Models.NicoVideoQuality x)\r\n   at System.Reactive.Linq.ObservableImpl.Select<NicoPlayerHohoema.Models.NicoVideoQuality,System.String>._.OnNext(Models.NicoVideoQuality value)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Reactive.PlatformServices.DefaultExceptionServices.Rethrow(Exception exception)\r\n   at System.Reactive.ExceptionHelpers.Throw(Exception exception)\r\n   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)\r\n   at System.Reactive.AnonymousSafeObserver<<>f__AnonymousType0<NicoPlayerHohoema.Models.Subscription.Subscription,NicoPlayerHohoema.Models.Subscription.SubscriptionSource>>.OnError(Exception error)\r\n   at System.Reactive.Linq.ObservableImpl.Select<NicoPlayerHohoema.Models.NicoVideoQuality,System.String>._.OnNext(Models.NicoVideoQuality value)\r\n   at System.Reactive.Linq.ObservableImpl.Defer<NicoPlayerHohoema.Models.NicoVideoQuality>._.OnNext(Models.NicoVideoQuality value)\r\n   at System.Reactive.Linq.ObservableImpl.Concat<NicoPlayerHohoema.Models.NicoVideoQuality>._.OnNext(Models.NicoVideoQuality value)\r\n   at System.Reactive.Linq.ObservableImpl.ToObservable<NicoPlayerHohoema.Models.NicoVideoQuality>._.LoopRec(Reactive.Linq.ObservableImpl.ToObservable<NicoPlayerHohoema.Models.NicoVideoQuality>._.State state, Action<System.Reactive.Linq.ObservableImpl.ToObservable<NicoPlayerHohoema.Models.NicoVideoQuality>._.State> recurse)\r\n   at System.Reactive.Concurrency.Scheduler.<>c__DisplayClass49_0<System.Action<System.Action>>.<InvokeRec1>b__0(Action<System.Action> state1)\r\n   at NicoPlayerHohoema!<BaseAddress>+0x1dd4a91\r\n   at NicoPlayerHohoema!<BaseAddress>+0x18512d7\r\n   at SharedLibrary!<BaseAddress>+0x4f3429\r\n   at SharedLibrary!<BaseAddress>+0x4f2b74\r\n   at SharedLibrary!<BaseAddress>+0x4f22dd\r\n   at SharedLibrary!<BaseAddress>+0x4f2211\r\n   at SharedLibrary!<BaseAddress>+0x4f2122\r\n   at SharedLibrary!<BaseAddress>+0x38ba91\r\n   at NicoPlayerHohoema!<BaseAddress>+0x1dd8275\r\n   at SharedLibrary!<BaseAddress>+0x4f3429\r\n   at SharedLibrary!<BaseAddress>+0x4f2b74\r\n   at SharedLibrary!<BaseAddress>+0x4f22dd\r\n   at SharedLibrary!<BaseAddress>+0x4f2211\r\n   at SharedLibrary!<BaseAddress>+0x4f2122\r\n   at NicoPlayerHohoema!<BaseAddress>+0x1b2a6ee\r\n   at System.Reactive.Linq.ObservableImpl.ToObservable<NicoPlayerHohoema.Models.NicoVideoQuality>._.Run()\r\n   at System.Reactive.Linq.ObservableImpl.ToObservable<NicoPlayerHohoema.Models.NicoVideoQuality>.Run(IObserver<NicoPlayerHohoema.Models.NicoVideoQuality> observer, IDisposable cancel, Action<System.IDisposable> setSink)\r\n   at System.Reactive.Producer<NicoPlayerHohoema.Models.NicoVideoQuality>.SubscribeRaw(IObserver<NicoPlayerHohoema.Models.NicoVideoQuality> observer, Boolean enableSafeguard)\r\n   at System.ObservableExtensions.SubscribeSafe(IObservable<NicoPlayerHohoema.Models.NicoVideoQuality> source, IObserver<NicoPlayerHohoema.Models.NicoVideoQuality> observer)\r\n   at System.Reactive.TailRecursiveSink<NicoPlayerHohoema.Models.NicoVideoQuality>.MoveNext()\r\n   at System.Action.Invoke()\r\n   at System.Reactive.Concurrency.AsyncLock.Wait(Action action)\r\n   at System.Reactive.TailRecursiveSink<NicoPlayerHohoema.Models.NicoVideoQuality>.<Run>b__7_0(Action self)\r\n   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__47_0(Action<System.Action> _action, Action<System.Action<System.Action>> self)\r\n   at System.Reactive.Concurrency.Scheduler.<>c__DisplayClass49_0<System.Action<System.Action>>.<InvokeRec1>b__0(Action<System.Action> state1)\r\n   at NicoPlayerHohoema!<BaseAddress>+0x1dd4a91\r\n   at NicoPlayerHohoema!<BaseAddress>+0x18512d7\r\n   at SharedLibrary!<BaseAddress>+0x4f3429\r\n   at SharedLibrary!<BaseAddress>+0x4f2b74\r\n   at SharedLibrary!<BaseAddress>+0x4f22dd\r\n   at SharedLibrary!<BaseAddress>+0x4f2211\r\n   at SharedLibrary!<BaseAddress>+0x4f2122\r\n   at SharedLibrary!<BaseAddress>+0x38ba91\r\n   at NicoPlayerHohoema!<BaseAddress>+0x1dd8275\r\n   at SharedLibrary!<BaseAddress>+0x4f3429\r\n   at SharedLibrary!<BaseAddress>+0x4f2b74\r\n   at SharedLibrary!<BaseAddress>+0x4f22dd\r\n   at SharedLibrary!<BaseAddress>+0x4f2211\r\n   at SharedLibrary!<BaseAddress>+0x4f2122\r\n   at NicoPlayerHohoema!<BaseAddress>+0x1b2a6ee\r\n   at System.Reactive.Concurrency.Scheduler.Schedule(Reactive.Concurrency.IScheduler scheduler, Action<System.Action> action)\r\n   at System.Reactive.TailRecursiveSink<NicoPlayerHohoema.Models.NicoVideoQuality>.Run(Collections.Generic.IEnumerable<System.IObservable<NicoPlayerHohoema.Models.NicoVideoQuality>> sources)\r\n   at System.Reactive.Linq.ObservableImpl.Concat<NicoPlayerHohoema.Models.NicoVideoQuality>.Run(IObserver<NicoPlayerHohoema.Models.NicoVideoQuality> observer, IDisposable cancel, Action<System.IDisposable> setSink)\r\n   at System.Reactive.Producer<NicoPlayerHohoema.Models.NicoVideoQuality>.SubscribeRaw(IObserver<NicoPlayerHohoema.Models.NicoVideoQuality> observer, Boolean enableSafeguard)\r\n   at System.ObservableExtensions.SubscribeSafe(IObservable<NicoPlayerHohoema.Models.NicoVideoQuality> source, IObserver<NicoPlayerHohoema.Models.NicoVideoQuality> observer)\r\n   at System.Reactive.Linq.ObservableImpl.Defer<NicoPlayerHohoema.Models.NicoVideoQuality>._.Run()\r\n   at System.Reactive.Linq.ObservableImpl.Defer<NicoPlayerHohoema.Models.NicoVideoQuality>.Run(IObserver<NicoPlayerHohoema.Models.NicoVideoQuality> observer, IDisposable cancel, Action<System.IDisposable> setSink)\r\n   at System.Reactive.Producer<NicoPlayerHohoema.Models.NicoVideoQuality>.SubscribeRaw(IObserver<NicoPlayerHohoema.Models.NicoVideoQuality> observer, Boolean enableSafeguard)\r\n   at System.ObservableExtensions.SubscribeSafe(IObservable<NicoPlayerHohoema.Models.NicoVideoQuality> source, IObserver<NicoPlayerHohoema.Models.NicoVideoQuality> observer)\r\n   at System.Reactive.Linq.ObservableImpl.Select<NicoPlayerHohoema.Models.NicoVideoQuality,System.String>.Run(IObserver<System.String> observer, IDisposable cancel, Action<System.IDisposable> setSink)\r\n   at System.Reactive.Producer<<>f__AnonymousType0<NicoPlayerHohoema.Models.Subscription.Subscription,NicoPlayerHohoema.Models.Subscription.SubscriptionSource>>.Run(Reactive.Concurrency.IScheduler _, Reactive.Producer<<>f__AnonymousType0<NicoPlayerHohoema.Models.Subscription.Subscription,NicoPlayerHohoema.Models.Subscription.SubscriptionSource>>.State x)\r\n   at NicoPlayerHohoema!<BaseAddress>+0x1854068\r\n   at System.Reactive.Concurrency.ScheduledItem<System.TimeSpan,System.Reactive.Producer<<>f__AnonymousType0<NicoPlayerHohoema.Models.Subscription.Subscription,NicoPlayerHohoema.Models.Subscription.SubscriptionSource>>.State>.InvokeCore()\r\n   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(Reactive.Concurrency.SchedulerQueue<System.TimeSpan> queue)\r\n   at NicoPlayerHohoema!<BaseAddress>+0x1dd9122\r\n   at SharedLibrary!<BaseAddress>+0x4f3429\r\n   at SharedLibrary!<BaseAddress>+0x4f2b74\r\n   at SharedLibrary!<BaseAddress>+0x4f22dd\r\n   at SharedLibrary!<BaseAddress>+0x4f2211\r\n   at SharedLibrary!<BaseAddress>+0x4f2122\r\n   at SharedLibrary!<BaseAddress>+0x4f3429\r\n   at SharedLibrary!<BaseAddress>+0x4f2b74\r\n   at SharedLibrary!<BaseAddress>+0x4f22dd\r\n   at SharedLibrary!<BaseAddress>+0x4f2211\r\n   at SharedLibrary!<BaseAddress>+0x4f2122\r\n   at NicoPlayerHohoema!<BaseAddress>+0x1dd7f96\r\n   at SharedLibrary!<BaseAddress>+0x4f3429\r\n   at SharedLibrary!<BaseAddress>+0x4f2b74\r\n   at SharedLibrary!<BaseAddress>+0x4f22dd\r\n   at SharedLibrary!<BaseAddress>+0x4f2211\r\n   at SharedLibrary!<BaseAddress>+0x4f2122\r\n   at System.Reactive.Producer<<>f__AnonymousType0<NicoPlayerHohoema.Models.Subscription.Subscription,NicoPlayerHohoema.Models.Subscription.SubscriptionSource>>.SubscribeRaw(IObserver<<>f__AnonymousType0<NicoPlayerHohoema.Models.Subscription.Subscription,NicoPlayerHohoema.Models.Subscription.SubscriptionSource>> observer, Boolean enableSafeguard)\r\n   at System.Reactive.Producer<<>f__AnonymousType0<NicoPlayerHohoema.Models.Subscription.Subscription,NicoPlayerHohoema.Models.Subscription.SubscriptionSource>>.Subscribe(IObserver<<>f__AnonymousType0<NicoPlayerHohoema.Models.Subscription.Subscription,NicoPlayerHohoema.Models.Subscription.SubscriptionSource>> observer)\r\n   at NicoPlayerHohoema!<BaseAddress>+0x1b431f9\r\n   at Reactive.Bindings.ReactiveProperty<Prism.Windows.Mvvm.ViewModelBase>..ctor(IObservable<Prism.Windows.Mvvm.ViewModelBase> source, Reactive.Concurrency.IScheduler raiseEventScheduler, Windows.Mvvm.ViewModelBase initialValue, Bindings.ReactivePropertyMode mode, Collections.Generic.IEqualityComparer<Prism.Windows.Mvvm.ViewModelBase> equalityComparer)\r\n   at NicoPlayerHohoema!<BaseAddress>+0x1dc32ba\r\n   at NicoPlayerHohoema.ViewModels.PlayerSidePaneContent.SettingsSidePaneContentViewModel..ctor(Models.NGSettings ngSettings, Models.PlayerSettings playerSettings, Models.PlaylistSettings playlistSettings)\r\n   at NicoPlayerHohoema!<BaseAddress>+0x1d7e9f7\r\n   at SharedLibrary!<BaseAddress>+0x4afb00\r\n   at SharedLibrary!<BaseAddress>+0x45ef1e\r\n   at SharedLibrary!<BaseAddress>+0x60996a\r\n   at SharedLibrary!<BaseAddress>+0x4d8450\r\n   at SharedLibrary!<BaseAddress>+0x4d82cd\r\n   at SharedLibrary!<BaseAddress>+0x38a168\r\n   at SharedLibrary!<BaseAddress>+0x389cf2\r\n   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicBuildPlanGenerationContext.<>c__DisplayClass16_0.<GetBuildMethod>b__0(Builder.IBuilderContext context)\r\n   at LiteDB.LiteQueryable<NicoPlayerHohoema.Database.Bookmark>.<>c__DisplayClass8_0.<ForEach>b__0(Database.Bookmark a, Int32 i)\r\n   at Unity.ObjectBuilder.Strategies.BuildPlanStrategy.PreBuildUp(Builder.IBuilderContext context)\r\n   at Unity.Container.StrategyChain.BuildUp(Builder.IBuilderContext builderContext)\r\n   at Unity.Policy.BuildPlanPolicyExtensions.ExecuteBuildUp(Policy.IBuildPlanPolicy policy, Builder.IBuilderContext context)\r\n   at Unity.UnityContainer.BuildUp(Type typeToBuild, Object existing, String name, Resolution.ResolverOverride[] resolverOverrides)\r\n   Exception_EndOfInnerExceptionStack\r\n   at Unity.UnityContainer.BuildUp(Type typeToBuild, Object existing, String name, Resolution.ResolverOverride[] resolverOverrides)\r\n   at Unity.UnityContainer.Resolve(Type type, String name, Resolution.ResolverOverride[] resolverOverrides)\r\n   at NicoPlayerHohoema!<BaseAddress>+0x1cda523\r\n   at NicoPlayerHohoema.ViewModels.LivePlayerPageViewModel.GetSidePaneContent(Nullable<NicoPlayerHohoema.ViewModels.PlayerSidePaneContentType> maybeType)\r\n   at System.Reactive.Linq.ObservableImpl.Select<System.Nullable<NicoPlayerHohoema.ViewModels.PlayerSidePaneContentType>,System.String>._.OnNext(Nullable<NicoPlayerHohoema.ViewModels.PlayerSidePaneContentType> value)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Reactive.PlatformServices.DefaultExceptionServices.Rethrow(Exception exception)\r\n   at System.Reactive.ExceptionHelpers.Throw(Exception exception)\r\n   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex)\r\n   at System.Reactive.AnonymousSafeObserver<<>f__AnonymousType0<NicoPlayerHohoema.Models.Subscription.Subscription,NicoPlayerHohoema.Models.Subscription.SubscriptionSource>>.OnError(Exception error)\r\n   at System.Reactive.ScheduledObserver<System.Reactive.EventPattern<NicoPlayerHohoema.Models.Cache.NicoVideoCacheProgress>>.Run(Object state, Action<System.Object> recurse)\r\n   at System.Reactive.Concurrency.Scheduler.<>c__DisplayClass49_0<System.Action<System.Action>>.<InvokeRec1>b__0(Action<System.Action> state1)\r\n   at NicoPlayerHohoema!<BaseAddress>+0x1dd4a91\r\n   at NicoPlayerHohoema!<BaseAddress>+0x18512d7\r\n   at SharedLibrary!<BaseAddress>+0x4f3429\r\n   at SharedLibrary!<BaseAddress>+0x4f2b74\r\n   at SharedLibrary!<BaseAddress>+0x4f22dd\r\n   at SharedLibrary!<BaseAddress>+0x4f2211\r\n   at SharedLibrary!<BaseAddress>+0x4f2122\r\n   at SharedLibrary!<BaseAddress>+0x38ba91\r\n   at System.Reactive.Concurrency.SynchronizationContextScheduler.<>c__DisplayClass4_0<>.<Schedule>b__0()\r\n   at SharedLibrary!<BaseAddress>+0x4f3429\r\n   at SharedLibrary!<BaseAddress>+0x4f2b74\r\n   at SharedLibrary!<BaseAddress>+0x4f22dd\r\n   at SharedLibrary!<BaseAddress>+0x4f2211\r\n   at SharedLibrary!<BaseAddress>+0x4f2122\r\n   at System.Action.Invoke()\r\n   at System.Reactive.Concurrency.SynchronizationContextExtensions.<>c__DisplayClass1_0.<PostWithStartComplete>b__0(Object _)\r\n   at SharedLibrary!<BaseAddress>+0x4f5158\r\n   at SharedLibrary!<BaseAddress>+0x4f54bc",
  "IsInternetAvailable": true,
  "IsLoggedIn": true,
  "IsPremiumAccount": false
}

**Comment by nishizumi-lab** [comment]
Hohoemaを再インストールしたら正常に動作しました。
（設定アイコンから開けました）
