### ISSUE TITLE
[0.16.1] マイリストの内容が表示されない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#754]
以下のバージョンからだと思うのですが、マイリスト、ローカルマイリストともに内容が表示されないようです。
動画によっては？表示される場合もあります。
#610 と関連があるかは不明です。

**環境：**
- Windows10 Pro 1809
- v0.16.1
![mylist1](https://user-images.githubusercontent.com/5137077/50085028-327f2f00-023c-11e9-9340-c856775a3dc9.png)

**Comment by tor4kichi** [comment]
こちらでも確認しました。使い勝手に直結する問題なので早々に対応したいと思います。

ただ、今現在リファクタリング作業（という名の大規模な設計の見直し）をしていてアイテムメニューもその中で改善を加える予定なので、hotfixとして早々に修正を出すと手戻りがそれなりに辛いことになりそう…と、やや時間を置いての更新になりそうです。

（年が変わる前までにはなんとか）

**Comment by kometchtech** [comment]
>こちらでも確認しました。使い勝手に直結する問題なので早々に対応したいと思います。
ありがとうございます。

対応お待ちしております。

>ただ、今現在リファクタリング作業（という名の大規模な設計の見直し）をしていてアイテムメニューもその中で改善を加える予定なので、hotfixとして早々に修正を出すと手戻りがそれなりに辛いことになりそう…と、やや時間を置いての更新になりそうです。

リファクタリングの方、優先されて下さい。手戻りは怖いのでその方が良いと思いますよー
お手伝いできれば良いのですが、.Netは分からず・・・

**Comment by kometchtech** [comment]
0.17.4では今のところ問題なさそうです。
