### ISSUE TITLE
マイリストに登録できない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#755]
今さら気が付きましたが、 #754 と関連しているのか、動画のマイリストへの登録もできないようになっていますね。

**追記：**
説明が不足していたので追記します。
別ウィンドウで動画再生した場合、別ウィンドウからマイリスト登録しようとしても反応しないようです。

**環境：**
- Windows 10 Pro 1809
- v0.16.1

**関連：**
#547 #754

**Comment by tor4kichi** [comment]
作業中のバージョンではマイリスト登録（別ウィンドウ時も含む）対応できている状態なので、本件も更新のリリースをお待ちください💦

ちなみにリファクタリング（という名の大規模改修）はもう少しで完了予定ですので早くて年内、遅くても年明け早々にはテスト版リリースできようかと思いますー。

**Comment by kometchtech** [comment]
私は全然気にしませんので、そちらのペースでご対応いただければ・・・
※年末進行ですしね・・・

**Comment by kometchtech** [comment]
0.17.4では問題なさそうです。

**Comment by kometchtech** [comment]
マイリストに追加しようとすると以下のようなエラーメッセージが出力されますね。

```
ErrorMessage": "System.InvalidCastException: InvalidCast_ComSystem.__ComObject, System.ComponentModel.PropertyChangedEventHandler, {50F19C16-0A22-4D8E-A089-1EA9951657D2}, インターフェイスがサポートされていません (Excep_FromHResult 0x80004002). 
```
[Hohoema-0_18_2_0-ffwrh3h0.txt](https://github.com/tor4kichi/Hohoema/files/2929623/Hohoema-0_18_2_0-ffwrh3h0.txt)
[Hohoema-0_18_2_0-ttwepyyc.txt](https://github.com/tor4kichi/Hohoema/files/2929624/Hohoema-0_18_2_0-ttwepyyc.txt)
