### ISSUE TITLE
[0.17.0] マイリストに追加後、メッセージがフェードアウトしない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#758]
0.17.0にアップデートしてから、マイリストに動画を追加すると、追加のメッセージがUI下部に表示されますが、一定時間経過してもフェードアウトしないようです。
以前までのバージョンであればフェードアウトしていたと思うのですが・・・

※0.17ではリファクタリングされるということでしたので、Todoに入っていたら申し訳ありません。

**環境：**
- 0.17.0
- Windows 10 Pro 1809

![hohoema](https://user-images.githubusercontent.com/5137077/50685629-48268e00-105d-11e9-91e9-bd1d54cde31c.png)

**Comment by tor4kichi** [comment]
ご報告ありがとうございます。

通知系の処理を切り出して整理した際の対応漏れで表示時間設定してないことが原因、と思います。対応しますー。

**Comment by tor4kichi** [comment]
ほんとだ😨

**Comment by kometchtech** [comment]
0.17.4で、問題なく表示されますし、一定時間後フェードアウトすることを確認しました。

ご対応ありがとうございましたー

**Comment by kometchtech** [comment]
以下のバージョンでマイリストへの追加をしたところ、追加した旨のメッセージが出力されないようです。

- Windows 10 Pro 1809
- 0.18.2

**Comment by kometchtech** [comment]
すみません、アプリを再起動したところ問題が解消しました。
その後は再発していません。

お手数をおかけしました。

**Comment by kometchtech** [comment]
すみません、やはり表示されない時があるようです。

また、ローカルマイリストに登録しようとして、クリック一回では有効にならず、2回クリックが必要になる時があります。

[Hohoema-0_18_2_0-0hk2xh4l.txt](https://github.com/tor4kichi/Hohoema/files/2929604/Hohoema-0_18_2_0-0hk2xh4l.txt)
[Hohoema-0_18_2_0-ld4y2dop.txt](https://github.com/tor4kichi/Hohoema/files/2929605/Hohoema-0_18_2_0-ld4y2dop.txt)
