### ISSUE TITLE
視聴履歴の個別削除

### ISSUE THREAD

**Issue by doreddono-to** [tor4kichi/Hohoema#760]
履歴の削除で削除したい動画にチェックを入れて一気に削除する以前の使用に戻してほしいです。
一つ一つ右クリックからやっていくのが面倒になっるので。

**Comment by tor4kichi** [comment]
ですよね。

履歴を残したくないっていう動機に対してアプリが対応できるようにしていきたいですが、複数選択復活の形ではないかもしれません。

正直言って複数選択の実装や維持管理は面倒くさいので（必要ならやりますが）できれば避けたい。

「今日見た分だけ消したい」「特定のタグを含む履歴だけ消したい」とか「消したい動機に基づいたアクション」について何かいいアイデアがあったら聞かせてください。

**Comment by doreddono-to** [comment]
返信遅れて申し訳ない。
複数選択ではなくても公式の視聴履歴みたいな動画ごとの「履歴から削除」ボタン
でも個人的にはおkです。
ただ専用アプリは公式以上の機能を求めているという意味では、複数選択復活してほしいと思っています^^;

**Comment by doreddono-to** [comment]
返信遅れて申し訳ない。
複数選択ではなくても公式の視聴履歴みたいな動画ごとの「履歴から削除」ボタン
でも個人的にはおkです。
右クリック→この履歴を消去するという項目を選ぶ一連の動作が一番めんどくさく感じているので。
ただ専用アプリは公式以上の機能を求めているという意味では、複数選択復活してほしいと思っていますが^^;
