### ISSUE TITLE
[0.17.3] ピン留めした検索結果をクリックしても一覧が表示されない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#765]
ピン留めした検索結果をクリックしても、検索結果一覧が表示され内容です。
更新ボタンをクリックしても一覧は更新されませんでした。

**環境：**
- 0.17.3
- Windows 10 Pro 1809

**Comment by kometchtech** [comment]
すみません、時間をおいて確認したところ表示されるようになりました。

**Comment by kometchtech** [comment]
ピン留めした結果の一番上にある結果しか一覧に表示されないようです。
アプリを再起動してもこの問題は改善しませんでした。

**Comment by kometchtech** [comment]
> ピン留めを再度登録して貰えると動くかなと思います。お手数おかけしますがよれけばお試しください。

ピン留めを解除後、再度ピン留め（登録）してみましたが、やはり検索結果一覧は表示されないようです。

kiichi toura wrote:

**Comment by tor4kichi** [comment]
問題が起きる検索キーワードと対象（キーワードかタグか等）をお聞きしてもいいですか？

**Comment by kometchtech** [comment]
画像で失礼します（嗜好がばれる）。
また、一応、jsonファイルなども添付しますね。

![search](https://user-images.githubusercontent.com/5137077/51225864-fac8eb80-198f-11e9-998f-d4d9bd71f9a8.png)
[0_17_3.zip](https://github.com/tor4kichi/Hohoema/files/2762595/0_17_3.zip)

**Comment by tor4kichi** [comment]
助かります_(._.)_

**Comment by kometchtech** [comment]
すみません、書き忘れていました。
一番上にある「ZYTOKINE」のみ検索結果一覧が表示される状態で、2個目以降は表示されない（それぞれをクリックしても反応しない）状態です。

**Comment by tor4kichi** [comment]
頂いた情報のおかげで原因がわかりまして、意外なところで日本語含むキーワードで引っかかってました。（アプリ内のパラメータ渡しがURLベースに変わったため起きたバグでした）

修正の申請を先ほど出したので明日の朝には利用可能になってると思います。ご協力感謝です👍

**Comment by kometchtech** [comment]
ご対応ありがとうございます。
文字のエンコードの問題でしたかー

アップデート出来次第確認して、報告させていただきますね。

**Comment by kometchtech** [comment]
0.17.4で問題なくピン留め検索結果をクリックして結果が表示されることを確認しました。

ご対応ありがとうございましたー
