### ISSUE TITLE
[0.17.4] アプリが強制終了する

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#768]
デバッグを有効にしていると、動画の再生終了後（最後まで再生されたとき）、強制終了するときがあるようです。
デバッグは有効にしていますが、デバッグログやメッセージトーストは表示されませんでした。

**関連：**
- #767 

**環境：**
- 0.17.4
- Windows 10 Pro 1809

**Comment by tor4kichi** [comment]
こちらでも一度だけ同様の症状に遭遇しましたが、原因は掴めず…。

その時は、

* 4~5動画ほど見た後に発生
* メインウィンドウで再生していた

ぐらいのインフォメーションしか思い当たりませんが、継続して見ていきたいと思います。
