### ISSUE TITLE
[0.18.0] ピン留めしたタグなどの位置が保存されない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#769]
たびたびすみません。
ピン留めしたタグの位置が保存されなくなりました。
状況としては直前にPCが強制再起動かかったあと、アプリを起動したところ、再起動前に移動していたピン留め情報の位置が最後尾に戻っていました。
アプリのリセットを行い、設定ファイルなどを書き戻しても状況は改善しませんでした。

**環境：**
- 0.18.0
- Windows 10 Pro 1809

**関連：**
#761

**Comment by tor4kichi** [comment]
再起動等はたぶん関係なく、保存するタイミングの設定が「ピンのラベルなどが変更された時」だけになっていたのが原因のようです。

（ユースケース実装側でピン留めの並べ替えの保存をトリガーしていたところから入れ替えのイベントに反応してモデル側で保存するようコードの整理をしていた、はずなんですが対応漏れていました）

対応していきます。

**Comment by kometchtech** [comment]
0.25.5にてこの問題が再発しているようで、手元の環境ではこの問題に遭遇しています。

- Windows 10 Pro 2004
