### ISSUE TITLE
[0.18.0] 登録したローカルマイリストがアプリを再起動後保存されていない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#770]
たぶん、 #769 と根っこは同じような気もしますが、登録したローカルマイリストがアプリ再起動後、ローカルマイリストを確認したところ、登録した動画が登録されていませんでした。

#769 同様、この症状が発生する前にPCの強制終了による再起動がありました。

デバッグログ等は出力されていません。

なんか色々と申し訳ありません。

**環境：**
- 0.18.0
- Windows 10 Pro 1809

**関連：**
#769

**Comment by kometchtech** [comment]
すみません、追加情報です。
デバッグログを有効にして、アプリを再起動したところ、いくつかのログが出力されるようになりました。

[Hohoema-0_18_0_0-xkajogkc.txt](https://github.com/tor4kichi/Hohoema/files/2772758/Hohoema-0_18_0_0-xkajogkc.txt)
[Hohoema-0_18_0_0-gsjywg5i.txt](https://github.com/tor4kichi/Hohoema/files/2772759/Hohoema-0_18_0_0-gsjywg5i.txt)
[Hohoema-0_18_0_0-wti0i1ch.txt](https://github.com/tor4kichi/Hohoema/files/2772760/Hohoema-0_18_0_0-wti0i1ch.txt)

**Comment by tor4kichi** [comment]
ありがとうございます。こちらでも再現できました。

各ローカルマイリストの変更検出処理がローカルマリイストの作成時しか付与できてなかったことが原因のようでした。

対応していきます。
