### ISSUE TITLE
Upper part of buttons at the top of VideoPlayerPage is not clickable in tablet mode

### ISSUE THREAD

**Issue by JasonWei512** [tor4kichi/Hohoema#775]
Hohoema Version: 0.18.2 
In tablet mode, upper part of buttons at the top of VideoPlayerPage is not clickable. (because they're overlapped by titlebar area?)

When mouse cursor is below titlebar area, the button is clickable and there's a reveal highlight effect:
![1_1](https://user-images.githubusercontent.com/16899918/53947993-dc66ad00-4101-11e9-9ed2-1459a7a2b7a0.jpg)

![1_2](https://user-images.githubusercontent.com/16899918/53947994-de307080-4101-11e9-814a-e04f5802af52.jpg)

![1_3](https://user-images.githubusercontent.com/16899918/53948023-e5f01500-4101-11e9-9fb2-721941998494.jpg)

When mouse cursor is in titlebar area, the button is not clickable and there is no reveal highlight effect:

![2_1](https://user-images.githubusercontent.com/16899918/53948033-ea1c3280-4101-11e9-8bb9-5705c5746b3c.jpg)

![2_2](https://user-images.githubusercontent.com/16899918/53948036-eb4d5f80-4101-11e9-9bfe-4962cba6674b.jpg)

![2_3](https://user-images.githubusercontent.com/16899918/53948039-ec7e8c80-4101-11e9-8d8a-c127cc17e825.jpg)

**Comment by tor4kichi** [comment]
thank you feedback and PR!

i have merged PR, and will release v0.18.7 after few days later.
