### ISSUE TITLE
チャンネル動画の暗号化に対応

### ISSUE THREAD

**Issue by tor4kichi** [tor4kichi/Hohoema#778]
https://blog.nicovideo.jp/niconews/100724.html

> 2019年3月5日に、一部のチャンネル動画をコンテンツの著作権保護を目的に、順次配信の暗号化を有効にする対応を実施しました。

**Comment by tor4kichi** [comment]
HLSの暗号化についてはUWPのAdaptiveMediaSource+MediaPlayerによってサポートされているため、映像処理周りではほとんど作業は必要ありませんでした。

暗号化が有効なHLSのMediaSegmentを取得するアクセス制御部分について、視聴ページの動作を模倣して以下のように対応しました。

* `https://nvapi.nicovideo.jp/v1/2ab0cbaa/watch?t={tranking_id}` へのアクセス（OPTIONS/GET）（下記画像参照のこと）
* .tsを取得する際のリクエストヘッダーにOriginとリファラーを設定する

![image](https://user-images.githubusercontent.com/7813604/53950312-37eb6780-410f-11e9-8898-8513f6e29c75.png)

**Comment by kurema** [comment]
確認していないですが、暗号化周りの処理を見る限り上記の内容はHLSへの対応に見えます。
アニメ系のチャンネル動画でも暗号化されているものもされていないものもあります。
暗号化されている動画は以下などがあります。
* https://www.nicovideo.jp/watch/1546841947
* https://www.nicovideo.jp/watch/1515637762
* https://www.nicovideo.jp/watch/1547519642

暗号化関係の情報は視聴ページ``#js-initial-watch-dataのvideo.dmcInfo.encryption.hls_encryption_v1``にあるようです。

**Comment by kurema** [comment]
``playlist.m3u8``に``#EXT-X-KEY:METHOD=AES-128,URI="https://nvapi.nicovideo.jp/v1/license/hls?h=...``が含まれるので問題ないのかもしれません。
自分でも確認してみます。

**Comment by tor4kichi** [comment]
cc3fc9630a626acdd5ecd177a17baba485dbcc0d
