### ISSUE TITLE
勝手に動く

### ISSUE THREAD

**Issue by doreddono-to** [tor4kichi/Hohoema#785]
再生を一時停止して放置すると勝手に再生したり別の動画に移動したりしました。
あと他にピンどめを勝手に消そうとしたりされました。
その間マウス等には一切触れてません。

**Comment by tor4kichi** [comment]
問題報告される際はHohoemaのバージョンと端末の種類（デスクトップ・タブレット or モバイル or XboxOne）をお知らせください。

また、同じ問題が繰り返し発生して、問題を再現する手順がわからないとこちらとしては対応が難しいです。
