### ISSUE TITLE
複数のモニタ間でリフレッシュレートが異なると映像がカクつく

### ISSUE THREAD

**Issue by sigref** [tor4kichi/Hohoema#788]
【再現方法】
- メインモニタのリフレッシュレートを、サブモニタよりも高い値に設定する

【症状】
- サブモニタで動画を再生すると、映像がカクつく（コメントは滑らかに流れる）

【再現環境】
- 主モニタ： 144Hz
- 副モニタ： 60Hz

**Comment by tor4kichi** [comment]
詳しくはわかりませんが、おそらくWindows10側の問題と思われます。

参考記事： https://www.notebookcheck.net/Windows-10-2004-20H1-finally-gets-multi-monitor-refresh-rates-right.454143.0.html

記事によるとWindows 10 2004にて改善されたとありますので、2004へのアップグレードを（安定性が良くないと聞きますのでくれぐれも慎重に）ご検討ください。

**Comment by tor4kichi** [comment]
アプリ側としては何も対応できない問題と見受けられますのでクローズさせて頂きます。

**Comment by tor4kichi** [comment]
高Hzの方をメインディスプレイに設定すると解消されるかもしれません
https://claypier.com/dual-monitor-refresh-rate-fix/
