### ISSUE TITLE
NG共有機能が機能していない?

### ISSUE THREAD

**Issue by reika727** [tor4kichi/Hohoema#789]
当方技術方面にはあまり詳しくないので乱文になりますがご容赦ください。

[この動画](https://www.nicovideo.jp/watch/sm29146854)を見ているときに気づいたのですが、NG共有機能があまり機能していないように思えます。ブラウザ版のniconicoだとNG共有機能で非表示になるコメントが、Hohoemaだと「表示する共有NGスコアの設定」を「最大」にしても消えないコメントが多数見られました。
あとこの件とはまた別の原因のバグかもしれませんが、調査の過程で「ブラウザ版だと表示されるのにHohoemaだと表示されないコメント」も少数ですが見つかりました。
<details>
<summary>長いので折りたたみ</summary>
<pre>
<code>
以下は上述動画の4:27-9:17のコメントになります。
<br />
※1 ... ブラウザ版でNG共有レベルを「中」以上にすると消えるが、Hohoemaでは「表示する共有NGスコアの設定」を「最大」にしても消えない
※2 ... Hohoemaで「表示する共有NGスコアの設定」が「なし」でも表示されない
<br />
きた
きたああ
きたあああ
ええぞ(※2)
神曲
s(※2)
男のヴォーカル曲はウザいからイラネｗ(※1)
男のヴォーカル曲はウザいからイラねｗ(※1)
男のヴォーカル曲はウザいからいらネｗ(※1)
男のヴォーカル曲はウザいからイラネｗ(※1)
男のヴォーカル曲はウザいからイラネｗ(※1)
一番好きな曲ｋｔｋｒ
男のヴォーカル曲はウザいからいらネｗ(※1)
男のヴォカール曲はウザいからイラネｗ(※1)
ええやん
この曲大好き　ゲームも良かった
ゲームも曲も大好きだった
男のヴォーカル曲はウザいからイラネｗ(※1)
男のヴォーカル曲はウザいからいらネｗ(※1)
つなぎのワザは鉄板だな
男のヴォーカル曲はウザいからイラネｗ(※1)
いい曲だよね
わかってるな
/normal
この流れテンションあがる
男のヴォーカル曲はウザいからイラネｗ(※1)
これはいい。男Voでも聴ける
gj
豚星ｷﾀ━━━━(ﾟ∀ﾟ)━━━━!!
これすげえいい曲だよな
ありがとうこれをずっと探していた
謎の名曲
ええリフやん
いいね
/normal
そいやこのゲーム詰んだままだｗ
/normal
初めてきいた
いい歌だな
早く終われ(※1)
長い。早く終われ！(※1)
曲調はＯＰだけどＥＤのような歌詞なんだよなぁ
ここすき
普通にマジカッコイイ
普通に良い歌だな
いいね
俺でも生きてて良いのかな？
だめ
早く終われ！(※1)
長い(※1)
こんな風に誰かを抱きしめてみたかった
すげー良い曲
主神曲教えてくれてありがとう
変な歌(※1)
やっと終わりそうだ(※1)
詩がいいね
</code>
</pre>
</details>

Hohoemaのバージョンは0.19.7、OSはWindows10 Home(バージョン1903、OSビルド18362.535)です。

**Comment by tor4kichi** [comment]
ご報告頂きありがとうございます。

NGスコアの評価が機能していないようですね。一覧で頂いた内容拝見してみると、NG共有で弾かないと見るのが辛いものもあるようですし早めに対応したいと思います。

**Comment by tor4kichi** [comment]
v0.20.0の更新にてNG共有スコアの動作を修正しました。

もしも問題が継続するようでしたら再オープンの上、ご報告頂ければと思います。

**Comment by reika727** [comment]
NG共有できているみたいです。ご対応ありがとうございましたm(_ _)m
