### ISSUE TITLE
Change theme without restarting app

### ISSUE THREAD

**Issue by JasonWei512** [tor4kichi/Hohoema#790]
https://github.com/JasonWei512/Hohoema/tree/theme
↑ It's not finished yet, but basically works.
(BTW, looks like your repo is not up-to-date? Logging in and 生放送 does not work.)

- Set app's theme by setting the RequestedTheme of window content (which doesn't need to restart the app), instead of app's RequestedTheme.
```
if (Window.Current.Content is FrameworkElement frameworkElement) 
{ 
    frameworkElement.RequestedTheme = ElementTheme.Light / Dark / Default; 
}
```
- When creating second window, change the RequestedTheme of the second window's content before assigning it to Window.Current.Content.
- Use ThemeResource instead of StaticResource.
- Regenerate HTML content when app's theme changes. (Not finished)
- If Window.Current.Content's RequestedTheme is ElementTheme.Default, the app will follow the Win10 system theme.

**Comment by tor4kichi** [comment]
こんにちは。動いてますよ！ 12月末からHohoemaに戻ってきたところで、今はリファクタリングと「あとで見る」機能に手を入れてるところです。（実際の更新はもう少し先になりそうですが…。）

テーマ設定を再起動なしでできれば便利ですよね。書いて頂いた内容はとてもわかりやすいですし、提示いただいた情報からすると手間もかからなさそうなので対応したいと思います。

あと生放送見れないのは問題ですね。優先して取り組みたいと思います。

Thank you!

**Comment by JasonWei512** [comment]
> あと生放送見れないのは問題ですね

No no no, I mean, the Hohoema in Windows store works fine. But when I compiled from your Github code, I **can** watch 生放送, but I can not view 放送説明. So I thought your github code is older than the Windows store version, and I didn't implement "regenerate html content in 放送情報 page when theme changes".

![image](https://user-images.githubusercontent.com/16899918/72204573-8b0f1300-34b4-11ea-9b97-754daa22822d.png)

(The left one is the one in Windows store, the right one is your github code)

There is no problem with 生放送. Sorry I didn't make it clear 😅

**Comment by tor4kichi** [comment]
あー、生放送の視聴自体は問題ないんですね。（早とちりでコメントしてしまいました）

Theme変更対応を入れた状態でTheme変更した際、放送情報のHTML等の再生成（あるいはページ全体の正常な表示）に対応してないよ、ということなのかなと思います。

こちらでTheme変更に取り組む時にHTML周りも気を付ける必要があるということで、改めて了解しました!!

**Comment by tor4kichi** [comment]
再起動無しテーマ変更に対応した v0.20.1 を公開しました。機能の実装方法など提案頂きありがとうございました！

**Comment by JasonWei512** [comment]
I found a bug with Hohoema v0.20.2:
My Windows 10's system theme is set to "dark". Hohoema's theme is set to "light" ↓
![image](https://user-images.githubusercontent.com/16899918/74034847-14eac700-49f4-11ea-80b1-0f5d18789594.png)

I closedand reopened Hohoema, and when I set theme to "システム設定に準じる", the app window is still in light theme. However title bar color changed ↓
![image](https://user-images.githubusercontent.com/16899918/74034764-e66cec00-49f3-11ea-900c-76c010e2a184.png)
