### ISSUE TITLE
マイリストに登録しようとしても既存のリストが表示されない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#793]
メインウィンドウ、別窓ともに既存のマイリストに登録しようとしてマイリストが表示されません。

![paint1](https://user-images.githubusercontent.com/5137077/73651800-9545bb00-46c8-11ea-8f42-ce3e9c120421.png)
![paint2](https://user-images.githubusercontent.com/5137077/73651802-95de5180-46c8-11ea-9822-ec305af4d35f.png)

**動作環境**
- 0.20.2
- windows10 1909 x64

**Comment by tor4kichi** [comment]
動画プレイヤーからのマイリストへの追加等で選択肢が表示されてないですね。対応していきます。

**Comment by kometchtech** [comment]
0.20.5で表示されるようになっていることを確認しました。
ご対応ありがとうございます。
