### ISSUE TITLE
動画タイトルによるフィルタを有効にする、が動作しない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#794]
設定にて「動画タイトルによるフィルタを有効にする」を設定しましたが、フィルタが有効にならないようです。

![paint](https://user-images.githubusercontent.com/5137077/73652119-73006d00-46c9-11ea-95d6-efd772c6f0c5.png)
![paint2](https://user-images.githubusercontent.com/5137077/73652120-73006d00-46c9-11ea-8d67-f261711e767f.png)

**動作環境**
-  0.20.2
-  windows10 1909 x64

**Comment by tor4kichi** [comment]
リストアイテムの非表示状態などを管理するコードを改めた際に抜け落ちてました。対応していきます。

**Comment by kometchtech** [comment]
0.20.5で動作するようになっていることを確認しましたー
ご対応ありがとうございます。

**Comment by kometchtech** [comment]
0.25.5でこの問題が再発しているようです。

- 0.25.5
- Windows 10 Pro 2004

**Comment by tor4kichi** [comment]
v1.0.2 現在で問題ないと思われるのクローズします。また問題あるようなら再オープンお願いします。
