### ISSUE TITLE
関連情報が取得・更新されない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#796]
スクリーンショットだと分からないと思いますが、
動画を再生していると、2回目以降関連情報が更新されない、というか取得できていないようです。

![paint1](https://user-images.githubusercontent.com/5137077/74099988-dcbac400-4b6c-11ea-9b6d-877b00c93fe5.png)

- 0.20.5
- Windows10 Pro 1909 x64

**Comment by tor4kichi** [comment]
ありがとうございます。動画プレイヤーのUIをキャッシュするように変えた影響で、初期化済みフラグが立ったままの関連情報が更新できてなかったようです。対応していきます。

**Comment by kometchtech** [comment]
0.20.6で対応されているのを確認しました。
ご対応ありがとうございました。
