### ISSUE TITLE
別窓の場合、関連情報のサムネイルが表示されない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#797]
別窓で再生を行っている場合、関連情報のサムネイルが表示されないようです。

**別窓**
![paint_disp](https://user-images.githubusercontent.com/5137077/74138351-cd06b280-4c34-11ea-8e64-5909bde7e020.png)
**メインウィンドウ**
![paint_no_disp](https://user-images.githubusercontent.com/5137077/74138348-cb3cef00-4c34-11ea-8899-3849afa8ed29.png)

**環境**
- windows10 Pro 1909 x64
- 0.20.6

**関連**

- https://github.com/tor4kichi/Hohoema/issues/796

**Comment by tor4kichi** [comment]
ありがとうございます。こちらでも再現しました。メインウィンドウのスレッド以外だと画像キャッシュ機能が動作しないようでした。対応していきます。

**Comment by cyatarow** [comment]
(開発者ではありませんが)0.21.5で直っていることを確認しました。問題がなければこのIssueのクローズをお願いします。

**Comment by kometchtech** [comment]
すみません、以下の画像のようにまだ次パート動画のサムネイルが取得できていないことがあります。

![paint](https://user-images.githubusercontent.com/5137077/75305120-86e25d80-5888-11ea-8931-5fde94415cce.png)

ということでcloseできないかなという認識でした。

**Comment by tor4kichi** [comment]
次パート動画部分がまだサムネイル表示ができてないんですね。引き続き対応していきます。
