### ISSUE TITLE
[0.21.5](マイリスト)Hohoema上で視聴したことのない動画の投稿時間表示が「0001年1月1日 0:00投稿」になる

### ISSUE THREAD

**Issue by cyatarow** [tor4kichi/Hohoema#803]
![20200228_3](https://user-images.githubusercontent.com/26016252/75510398-36a50000-5a2e-11ea-9422-9245fdc3f79e.png)

画像中の「2007年12月10日 5:27投稿」のように、1回でもHohoema上で視聴すれば、正しい投稿時間表示になります。

**Comment by tor4kichi** [comment]
a5c3e34032d157581edc79fb574d7a94f3a377c0 にて対応しました。修正含むパッケージはリリース済みです。

**Comment by cyatarow** [comment]
修正を確認しました。
