### ISSUE TITLE
ニコ生が見れない

### ISSUE THREAD

**Issue by doreddono-to** [tor4kichi/Hohoema#805]
ニコニコ動画の方は見れますがニコ生の視聴ができません。
プレイヤーは出ますが何も起こりません。
エラーのログはこれでいいでしょうか。
{
  "DeviceType": "Windows.Desktop",
  "OperatingSystem": "WINDOWS",
  "OperatingSystemVersion": "10.0.18362.720",
  "OperatingSystemArchitecture": "X64",
  "ApplicationVersion": "0.21.5.0",
  "Time": "2020-04-03T23:53:18.04384+09:00",
  "RecentOpenedPageName": "RankingCategoryList",
  "ErrorMessage": "System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at NicoPlayerHohoema.Services.Player.PrimaryViewPlayerManager.ResolveContentName(String, INavigationParameters) + 0xf6\r\n   at NicoPlayerHohoema.Services.Player.PrimaryViewPlayerManager.<>c__DisplayClass7_0.<<NavigationAsync>b__0>d.MoveNext() + 0x458\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x21\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object) + 0x1e\r\n   at System.Action`1.Invoke(T) + 0x28\r\n   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore() + 0x33\r\n",
  "IsInternetAvailable": true,
  "IsLoggedIn": true,
  "IsPremiumAccount": true
}
おま環かもしれませんがよくわからないのでよろしくおねがいします。

**Comment by tor4kichi** [comment]
別口でも報告頂いていて対応してました。

v0.21.8にて生放送視聴周りは一旦対応完了しました。今日アップデートの申請を出したので、今日明日には利用可能になると思います。（アプデ取得にはストアからの手動更新必要と思います）

なおタイムシフト周りは一切触ってないので壊れたままかもしれませんが、今後ゆっくり対応していく予定です。TS除いたコミュニティ・チャンネル・公式の放送が問題なく見られると確認できたら、こちらの課題をクローズできればと思います。
