### ISSUE TITLE
NG共有機能が機能していない?

### ISSUE THREAD

**Issue by reika727** [tor4kichi/Hohoema#806]
たびたびすみません、このたび[以前](https://github.com/tor4kichi/Hohoema/issues/789)と同じ動画で同じ問題が発生してしまいました。NG設定を「超スーパー強」に設定しているのですが、やはりほとんどのコメントがそのまま表示されてしまいます。
PCの再起動とアプリのリセットは試したのですが改善は見られませんでした。

Hohoemaのバージョンは0.21.9、OSはWindows10 Home(バージョン2004、OSビルド19041.329)です。聞きたいことやご不明な点があればお申し付けください。

**Comment by tor4kichi** [comment]
仰るとおりNGScore指定が機能していませんでした。

設定データの構造をv0.21.7で変更していた際の対応漏れが原因でした。

v0.21.14 にて修正予定です。

**Comment by tor4kichi** [comment]
リリースしました -> v0.21.15

**Comment by reika727** [comment]
v0.21.16にてNG共有機能が動作していることを確認しました。
ご対応ありがとうございましたm(_ _)m

**Comment by tor4kichi** [comment]
確認頂きありがとうございます。この課題はクローズしておきますね。また何かありましたらお聞かせください。
