### ISSUE TITLE
v0.24.0へのアップデート失敗に伴うローカルマイリス情報の喪失

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#815]
**事象：**
v0.23.0からv0.24.0へアップデートを実施したところ、以下の画面で止まってしまったので
強制終了を実施し、再度実行したところ、ローカルのマイリストが消失していることに気がつきました。

![hohoema](https://user-images.githubusercontent.com/5137077/92996750-f24ffc00-f548-11ea-89cb-f8a0d963eaa8.png)

**一応試したこと：**
hohoema-backup.dbからhohoema.dbへの書き戻し（変わらず）

**環境：**
- Windows10 2004 Version 10.0.19041.508
- hohoema v0.24.0

**Comment by tor4kichi** [comment]
LiteDBをv4系からv5系に更新してアップグレード処理を導入したんですが、それがダメだったようです。v4系に戻したバージョンを早めに出していきます。

**Comment by tor4kichi** [comment]
LocalStateの _v3 というファイルにローカルマイリスト等の情報が入ってるのでそれが残っていれば復旧可能かもしれません。再インストール後の起動前にLocalStateへ _v3 ファイルを配置し、その後アプリを起動するとアプリに取り込まれるかと思います。

**Comment by kometchtech** [comment]
> 今後配信予定の v0.25.1 を再インストール後、アプリの起動前にLocalStateへ _v3 ファイルを配置し、その後アプリを起動するとアプリに取り込まれるかと思います。

v0.24.1が配信されていましたが、こちらでしょうか？
その後リストア手順から試してみた感じではローディング（ロゴ画面）から進まなくなりました・・・

**Comment by tor4kichi** [comment]
いいえ、v0.24.1ではなくv0.25.1です。一般リリースはこれからですのでもうしばしお待ちください。

テスタ―登録済みであれば既にv0.25.1が利用可能になってますが、一般リリースはこれから審査ですので今日中には、というところです。

**Comment by kometchtech** [comment]
> いいえ、v0.24.1ではなくv0.25.1です。一般リリースはこれからですのでもうしばしお待ちください。

ありがとうございます。
こちらの早とちりで申し訳ありません。一般リリースを待たせていただきます。

**Comment by tor4kichi** [comment]
こちらこそ変なところで面倒を起こしてしまってすみません。

今しがた審査が通ったようなので更新できるようになってるかと思いますので、更新お試しください。

**Comment by kometchtech** [comment]
v0.25.1へアップデートすることが出来たので確認してみました。
結論からいうと中途半端な形で復旧できました。

左メニュー上はOKでした。
![bookmark](https://user-images.githubusercontent.com/5137077/93032126-97aec100-f66a-11ea-81af-5e325c5753f2.png)

しかし各マイリストの中身が表示上おかしくなっていました。
![local_mylist](https://user-images.githubusercontent.com/5137077/93032145-b1e89f00-f66a-11ea-9d8e-c36fbeac9d84.png)

ただ項目の中身の情報は生きているようで、クリックすることで動画の再生は行われ、マイリストを読み込み直す（メニューを切り替えるなどして）と再生した動画の情報は表示されるようになりました。

**Comment by tor4kichi** [comment]
v0.25.2更新で対策しました。一個ずつ更新しなくても済むようになってると思います。

**Comment by kometchtech** [comment]
遅くなりました。
v0.25.2で問題が無くなっていることを確認しました。
ご対応ありがとうございました。
