### ISSUE TITLE
[0.26.3] 要望:自動アクション設定時の次パート移動

### ISSUE THREAD

**Issue by cube-Sugar** [tor4kichi/Hohoema#828]
`次パート動画を自動検出して移動`を`オン`にしている場合であっても、
再生完了時の自動アクションを`何もしない`以外に設定すると、自動アクションが起こり、次パートに移動しないようです。

`次パート動画を自動検出して移動`を`オン`している場合は、次パートがない場合のみアクションを実行する動作が期待されるように思います。

**動作環境**
- Windowsバージョン: windows10 20H2  x64
- アプリバージョン: 0.26.3

**Comment by tor4kichi** [comment]
自動移動が正しく発生しない問題がありますよね。対応していきます。

**Comment by tor4kichi** [comment]
#829 の問題は 8feb93b7466f0eabf60f059404c8210fd8724797 のコミットで修正済みですが、これは未リリースの0.26.5 に含まれる予定です。

**Comment by cube-Sugar** [comment]
[d88f724](https://github.com/tor4kichi/Hohoema/commit/9a3cb2e9fd81c1b5e9e04547f30170369fc0ddaf)で修正され、0.26.4に含まれリリースされたものであると勘違いしておりした。
誠に申し訳ありません。

**Comment by tor4kichi** [comment]
どのリリースにどのコミットが乗るのか知れる立場にないのですから勘違いも仕方ないです。

githubじゃなくてマシュマロ https://marshmallow-qa.com/tor4kichi から連絡頂いたほうがお互い負担が少なかろうと思いますので、よかった今後の軽微な要望やバグ報告の際はマシュマロでの連絡をご検討頂ければと思います。

なお、0.26.5の方は土日のうちにはリリースしますので、もうしばらくお待ちください。
