### ISSUE TITLE
 [0.26.4]メインウィンドウ視聴時において、次パート動画送りよりも再生後表示切替アクションがされる

### ISSUE THREAD

**Issue by cube-Sugar** [tor4kichi/Hohoema#829]
別ウィンドウで視聴している際は、自動アクションを設定している場合も次パートに移動しましたが、
メインウィンドウで視聴している場合は、自動アクションを設定している場合は次パートに移動しませんでした。

度々、申し訳ありません。

### 関連
#828 

### 再現性
- アンイストールやリセット、再起動後に再現

### 環境
-  Windowsバージョン: windows10 20H2 x64
-  アプリバージョン: 0.26.4

**Comment by tor4kichi** [comment]
こちら 8feb93b7466f0eabf60f059404c8210fd8724797 のコミットで修正済みです。 #828 と重複した問題ですので勝手ながら閉じます。再生後アクション周りは #828 でやり取りしましょう。
