### ISSUE TITLE
キャッシュ取得に失敗する

### ISSUE THREAD

**Issue by cube-Sugar** [tor4kichi/Hohoema#831]
キャッシュ取得に関して、以下2点の予期せぬ挙動を確認したため、ご報告致します。
* キャッシュ取得時に `DL失敗`となります。
* プログレスバーが0%から変化しません。
    - プログレスバーに関しましては、キャッシュ取得中にアプリを終了し、再起動することで、プログレスバーに妥当な値が表示されるようになります。
    - 再起動後に新たに取得開始したものは、0%から変化いたしません。

キャッシュ保存先を確認すると、\~.dmc_superhigh.mp4、\~.tmpといったファイルが生成されており、
mp4は、終始0バイトであり、エラーとなった後にも残ります。
tmpは、容量が増えて行きますが、途中でエラーとなり削除されます。(成功した場合のその動画のサイズと比べて小さいサイズの段階でエラーになっているようにみえます）

#### 確認した点
・同一動画であっても、キャッシュ取得に成功する場合と失敗する場合があります。
・キャッシュ先変更、アプリ再インストール後も再現致しました。
・Windows10のUTF8を有効にする機能は未使用になります。
・キャッシュを複数同時に取得すると失敗する確率が、一つずつ取得する場合に比べ高くなるように思えます。
・動画の視聴は問題なく行えています。

#### 動作環境 
Windowsバージョン: windows10 20H2 x64
アプリバージョン: v0.26.7

マシュマロより同様の投稿を行いましたが、その際エラーになってしまい送信の可否が不明であったため、
github にて投稿させていただきました。
同様の内容が、マシュマロにおいても届いていましたら申し訳ありません。

何卒、よろしくお願い致します。

**Comment by tor4kichi** [comment]
返答遅くなって申し訳ないです。
唐突かと思いますが内々に進めていたキャッシュ機能刷新を次期バージョンにて提供予定のため本件クローズさせてください。
