### ISSUE TITLE
マイリストの動画一覧が表示できないケースがある件

### ISSUE THREAD

**Issue by tor4kichi** [tor4kichi/Hohoema#832]
[マシュマロ](https://twitter.com/tor4kichi/status/1363786582982017024) からお知らせ頂きました。その後、具体的なマイリストIDも提供頂いたため原因がわかりました。

原因はマイリストに非公開動画が含まれる場合に、動画情報のシリアライズを行うタイミングで動画投稿者のIDがnullになっているため、null例外が発生して後続動画情報の表示に失敗していたようでした。

**Comment by kometchtech** [comment]
v0.28.5でローカルマイリストが全て表示されないことを確認しました。

* Windows 10 Pro 20H2

**Comment by tor4kichi** [comment]
ご報告頂きありがとうございます。こちらv0.28.8で解消予定です。

原因としては内部のイベント伝搬実装をPrism.EventAggregatorからMS.Toolkit.Messengerに切り替えたところメッセージ登録周りで問題が発生していたようです。
