### ISSUE TITLE
検索一覧の表示に時間がかかる

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#833]
v0.27.5 にアップデートしてから添付のように検索動画一覧の表示に時間が掛かるようになりました。
（スローなどの加工はせずタイムスケールは等倍です）
![hohoema_0275](https://user-images.githubusercontent.com/5137077/114294747-9566f500-9adb-11eb-81e0-ab4bf7f7012d.gif)

少なくともv0.27.4までにこのような問題は発生していませんでした。

* Windows 10 Pro x64 20H2
* Hohoema v0.27.5

**Comment by tor4kichi** [comment]
内部で使用していたユーザー名取得APIの応答が詰まることが原因のようで次のアプデで解消見込みです。

**Comment by kometchtech** [comment]
ご連絡遅くなりました。
既にMicrosoft storeでリリースされていたv0.27.7にアップデートしたところ、本件解消しておりました。

ご対応ありがとうございました。
