### ISSUE TITLE
バックアップから読み込むでマイリストが戻らない

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#834]
#833 の対応でhohoemaを初期化し、その後マイリストを戻そうとバックアップから読み込んだところ、マイリストが修復されないことに気が付きました。
バックアップの書き出し自体はv0.27.4で行ったもので読み込みを試しました。

* Windows 10 Pro x64 20H2

**Comment by tor4kichi** [comment]
こちらでも再現しました。バックアップ読み込み後にアプリを再起動したら表示されるようなので、単に表示更新忘れかもしれません。対応していきます。

**Comment by kometchtech** [comment]
ご連絡遅くなりました。
既にMicrosoft storeでリリースされていたv0.27.7にアップデートしたところ、本件解消しておりました。

ご対応ありがとうございました。

**Comment by kometchtech** [comment]
v0.28.2にアップデートしたところ、本件再発するようになっていました。
