### ISSUE TITLE
既に設定情報がある状態でのバックアップの読み込みに失敗する

### ISSUE THREAD

**Issue by kometchtech** [tor4kichi/Hohoema#837]
既存の設定情報がある（フィルタ情報など）状態でバックアップを読み込んだところ、
**「バックアップからの復元に失敗しました」**
と表示されリカバリー？に失敗します。

インストール直後の読み込みは問題がありません。

* Windows 10 Pro 20H2
* v0.28.5

**Comment by tor4kichi** [comment]
ご報告頂きありがとうございます。v0.28.8 で解消予定です。

原因としてはDictionaryにローカルマイリストIDを重複登録が発生することで復元時にエラーが発生していたようです。
