### ISSUE TITLE
投稿者を非表示に設定が機能していません

### ISSUE THREAD

**Issue by kakkou** [tor4kichi/Hohoema#839]
動画リストのコンテキストメニュからの`投稿者を非表示に設定`が機能していません。
またすでに非表示設定にしている場合の`非表示を解除`は動いてしまうようです・・・。

動作環境
 1.0.2

**Comment by tor4kichi** [comment]
こちらでも確認しました。早めに直しますね。

**Comment by kakkou** [comment]
1.2.8で問題が発生しないので修正されたと思われます。
