### ISSUE TITLE
Sorted video search results are in the reversed order

### ISSUE THREAD

**Issue by JasonWei512** [tor4kichi/Hohoema#854]
In Hohoema v1.0.12, when I select "投稿日時が新しい順" as the sort option on the search page, the oldest video is displayed first. That's the case for all the other sort options too: 再生時間, 再生数, マイリスト数...

![屏幕截图 2021-06-12 214229](https://user-images.githubusercontent.com/16899918/121778329-03f22d00-cbc9-11eb-8c3c-c767f9fce2fc.jpg)

![屏幕截图 2021-06-12 214152](https://user-images.githubusercontent.com/16899918/121778328-03599680-cbc9-11eb-8976-fa957841bfb3.jpg)

**Comment by tor4kichi** [comment]
maybe that translation issue. due to Asc/Desc Enum value miss casting.

I will try fix as soon. thank you report!

**Comment by JasonWei512** [comment]
Thank you for fixing this bug!

**Comment by tor4kichi** [comment]
Hohoema v1.1.0 is now publish to test users, and will be released to the public in a few days.
