### ISSUE TITLE
ニコ生が見れない

### ISSUE THREAD

**Issue by doreddono-to** [tor4kichi/Hohoema#888]
Hohoemaはニコ動視聴とFGOの公式生放送、ユーザーの生放送を見るのに使っていたのですが
ずっと以前からFGOの公式生が見れなくなり最近ユーザーの生放送も見れなくなりました。
FGO以外の公式生放送は見れるみたいです。
おま環もしれないですが正直わからないのですがどうか対照法ありましたらよろしくお願いします。

**Comment by tor4kichi** [comment]
お返事遅くなってすみません。今後タイミングが今度合えば確認してみたいと思います。

直近ですとおそらく ↓ ですよね。
https://live.nicovideo.jp/watch/lv337853388

たぶんFGO公式放送ではなく [Nアニメ ニコニコアニメスペシャル](https://ch.nicovideo.jp/channel/ch67) の公式生放送が全体的にダメな可能性があると思うので、近いうちに確認できればと思います。

Nアニメ ニコニコアニメスペシャルの放送予定
https://anime.nicovideo.jp/live/reserved-tokuban.html?from=nanime_live-reserved-ikkyo_list

------------------------------

もしご自身でHohoema利用中に問題を現認されてデバッグに協力いただけるようでしたらデバッグモードを有効にした上でエラーログの内容をお知らせください。

デバッグモードの有効にする方法とエラーログの確認方法はこちら
https://github.com/tor4kichi/Hohoema/wiki/Hohoema%E3%81%AE%E3%83%87%E3%83%90%E3%83%83%E3%82%B0%E3%83%A2%E3%83%BC%E3%83%89%E3%82%92%E6%9C%89%E5%8A%B9%E3%81%AB%E3%81%99%E3%82%8B

**Comment by tor4kichi** [comment]
生放送の画質に `6Mbps1080p30fps`  が追加されていたことで解析エラーが発生し視聴開始が正常に処理できていないことが原因のようでした。

こちらv1.4.1のアップデートで対応済みのため一旦クローズさせて頂きます。問題が継続していた場合は、再オープンしてくださいませ。
