### ISSUE TITLE
動画や生放送の画面をつまめない

### ISSUE THREAD

**Issue by doreddono-to** [tor4kichi/Hohoema#896]
動画や生放送を再生している画面がマウスでつまめません。
別ウインドウで再生するとメインはつまめますが再生している別ウインドウがつまめません。

**Comment by tor4kichi** [comment]
1. アプリバージョンとOSバージョンを記載してください。（設定ページの右上を右クリックすると「バージョン番号をコピー」できます）

2. 問題を整理したいのですが、「別ウィンドウを表示した時に、別ウィンドウのマウスによるウィンドウ移動が出来ない。ただし、メインウィンドウはウィンドウの移動は問題ない」ということで合ってますか？

私の方の環境ではウィンドウ移動ができなくなる問題は発生せず、問題を再現できないため対応は保留になりそうです。
